# RS3 Hsu2013-only model: fixed split, 100 Optuna trials

Place this notebook in `rs_dev/code` and run all cells.

In [1]:
from pathlib import Path
import json, warnings, joblib
import lightgbm as lgb
import numpy as np
import optuna
import pandas as pd
from scipy.stats import pearsonr, spearmanr
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import StratifiedGroupKFold
from datasets import dataset_list
from core import get_feature_df

TRACR_FILTER = "Hsu2013"
SPLIT_SEED = 42
OPTUNA_SEED = 42
MODEL_SEED = 42
N_TRIALS = 100
EARLY_STOPPING_ROUNDS = 10

PROCESSED_DIR = Path("../data/processed")
OUTPUT_DIR = Path("../models/rs3_hsu2013_fixed_split_100_trials")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
TRAIN_NAMES_FILE = PROCESSED_DIR / "train_data_names.csv"
print("Output:", OUTPUT_DIR.resolve())

/opt/anaconda3/envs/rs_dev_venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Output: /Users/zhangjiongyu/CRISPR-modular-deep-learning_backup_copy_revision/Revision_existing_model_comparison/RS3/rs_dev/models/rs3_hsu2013_fixed_split_100_trials

In [3]:
train_data_names = pd.read_csv(TRAIN_NAMES_FILE)["name"].dropna().astype(str).tolist()
train_data_list = [ds for ds in dataset_list if ds.name in train_data_names]

for ds in train_data_list:
    ds.load_data()
    ds.set_sgrnas()

sg_df_list = []
for ds in train_data_list:
    df = ds.get_sg_df(include_group=True, include_activity=True).copy()
    df["dataset"] = ds.name
    df["tracr"] = ds.tracr
    sg_df_list.append(df)

groups = (
    pd.concat(sg_df_list, ignore_index=True)
    .groupby("sgRNA Context Sequence", as_index=False)
    .agg(target=("sgRNA Target", lambda x: ", ".join(sorted({
        str(v).upper() for v in x if not pd.isna(v) and str(v).strip() != ""
    }))))
)
groups["target"] = groups.apply(
    lambda r: r["target"] if r["target"] != "" else r["sgRNA Context Sequence"],
    axis=1,
)

all_data = (
    pd.concat(sg_df_list, ignore_index=True)
    .merge(groups[["sgRNA Context Sequence", "target"]], on="sgRNA Context Sequence", how="inner")
    .sort_values(["dataset", "target"])
    .reset_index(drop=True)
)

all_data["sgRNA Activity"] = pd.to_numeric(all_data["sgRNA Activity"], errors="coerce")
all_data = all_data.dropna(subset=[
    "sgRNA Context Sequence", "sgRNA Activity", "dataset", "tracr", "target"
]).reset_index(drop=True)

print("Available tracr values:")
print(all_data["tracr"].value_counts(dropna=False))

filtered_data = all_data.loc[
    all_data["tracr"].astype(str) == TRACR_FILTER
].copy().reset_index(drop=True)

if filtered_data.empty:
    raise ValueError(f"No rows found for tracr={TRACR_FILTER!r}")

print("\nFiltered rows:", len(filtered_data))
display(filtered_data["dataset"].value_counts().rename("n").to_frame())

Available tracr values:
tracr
Hsu2013     29951
Chen2013    21136
Name: count, dtype: int64

Filtered rows: 29951

                      n
dataset
Kim2019_train     12832
Xiang2021         11397
Doench2016         2536
Doench2014_mouse   1169
Wang2014           1022
Doench2014_human    995

In [5]:
outer = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=SPLIT_SEED)
seen_idx, unseen_idx = next(outer.split(
    filtered_data, y=filtered_data["dataset"], groups=filtered_data["target"]
))
seen_data = filtered_data.iloc[seen_idx].reset_index(drop=True)
unseen_data = filtered_data.iloc[unseen_idx].reset_index(drop=True)

inner = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=SPLIT_SEED)
train_idx, val_idx = next(inner.split(
    seen_data, y=seen_data["dataset"], groups=seen_data["target"]
))
train_data = seen_data.iloc[train_idx].reset_index(drop=True)
validation_data = seen_data.iloc[val_idx].reset_index(drop=True)

assert set(train_data["target"]).isdisjoint(set(validation_data["target"]))
assert set(train_data["target"]).isdisjoint(set(unseen_data["target"]))
assert set(validation_data["target"]).isdisjoint(set(unseen_data["target"]))

display(pd.DataFrame({
    "subset": ["train", "validation", "unseen"],
    "n_rows": [len(train_data), len(validation_data), len(unseen_data)],
    "fraction": [
        len(train_data)/len(filtered_data),
        len(validation_data)/len(filtered_data),
        len(unseen_data)/len(filtered_data),
    ],
}))

       subset  n_rows  fraction
0       train   20949  0.699442
1  validation    4119  0.137525
2      unseen    4883  0.163033

In [7]:
X_train = get_feature_df(train_data)
X_validation = get_feature_df(validation_data).reindex(columns=X_train.columns, fill_value=0)
X_unseen = get_feature_df(unseen_data).reindex(columns=X_train.columns, fill_value=0)

y_train = train_data["sgRNA Activity"].to_numpy(float)
y_validation = validation_data["sgRNA Activity"].to_numpy(float)
y_unseen = unseen_data["sgRNA Activity"].to_numpy(float)

print(X_train.shape, X_validation.shape, X_unseen.shape)

100%|███████████████████████████████████| 20949/20949 [00:03<00:00, 5367.10it/s]
100%|█████████████████████████████████████| 4119/4119 [00:00<00:00, 5326.77it/s]
100%|█████████████████████████████████████| 4883/4883 [00:00<00:00, 5412.42it/s]

(20949, 632) (4119, 632) (4883, 632)

In [9]:
def safe_pearson(y_true, y_pred):
    if len(y_true) < 2 or np.std(y_true) == 0 or np.std(y_pred) == 0:
        return np.nan
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return float(pearsonr(y_true, y_pred)[0])

def safe_spearman(y_true, y_pred):
    if len(y_true) < 2 or np.std(y_true) == 0 or np.std(y_pred) == 0:
        return np.nan
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return float(spearmanr(y_true, y_pred)[0])

In [11]:
trial_records = []
trial_models = {}

def objective(trial):
    model = lgb.LGBMRegressor(
        objective="regression",
        random_state=MODEL_SEED,
        n_jobs=-1,
        learning_rate=0.01,
        n_estimators=5000,
        num_leaves=trial.suggest_int("num_leaves", 8, 256),
        min_child_samples=trial.suggest_int("min_child_samples", 8, 256),
        verbosity=-1,
    )

    model.fit(
        X_train, y_train,
        eval_set=[(X_validation, y_validation)],
        eval_metric="mse",
        callbacks=[lgb.early_stopping(EARLY_STOPPING_ROUNDS, verbose=False)],
    )

    best_iteration = model.best_iteration_ or model.n_estimators
    val_pred = model.predict(X_validation, num_iteration=best_iteration)
    unseen_pred = model.predict(X_unseen, num_iteration=best_iteration)

    validation_mse = float(mean_squared_error(y_validation, val_pred))
    unseen_pearson = safe_pearson(y_unseen, unseen_pred)
    unseen_spearman = safe_spearman(y_unseen, unseen_pred)

    trial.set_user_attr("best_iteration", int(best_iteration))
    trial_records.append({
        "trial": trial.number,
        "validation_mse": validation_mse,
        "unseen_pearson": unseen_pearson,
        "unseen_spearman": unseen_spearman,
    })
    trial_models[trial.number] = model

    print(
        f"Trial {trial.number:3d} | Validation MSE: {validation_mse:.6f} | "
        f"Unseen Pearson: {unseen_pearson:.4f} | "
        f"Unseen Spearman: {unseen_spearman:.4f}"
    )
    return validation_mse

study = optuna.create_study(
    direction="minimize",
    sampler=optuna.samplers.TPESampler(seed=OPTUNA_SEED),
)
study.optimize(objective, n_trials=N_TRIALS)

[I 2026-07-15 21:30:09,111] A new study created in memory with name: no-name-833169c6-8bf4-4450-a013-f22cf7f5b621
[I 2026-07-15 21:30:33,988] Trial 0 finished with value: 0.4489989451354644 and parameters: {'num_leaves': 101, 'min_child_samples': 244}. Best is trial 0 with value: 0.4489989451354644.

Trial   0 | Validation MSE: 0.448999 | Unseen Pearson: 0.7416 | Unseen Spearman: 0.7306

[I 2026-07-15 21:31:18,272] Trial 1 finished with value: 0.4500086247064298 and parameters: {'num_leaves': 190, 'min_child_samples': 157}. Best is trial 0 with value: 0.4489989451354644.

Trial   1 | Validation MSE: 0.450009 | Unseen Pearson: 0.7427 | Unseen Spearman: 0.7305

[I 2026-07-15 21:31:45,666] Trial 2 finished with value: 0.45261795647303016 and parameters: {'num_leaves': 46, 'min_child_samples': 46}. Best is trial 0 with value: 0.4489989451354644.

Trial   2 | Validation MSE: 0.452618 | Unseen Pearson: 0.7402 | Unseen Spearman: 0.7260

[I 2026-07-15 21:32:07,851] Trial 3 finished with value: 0.4503172814084963 and parameters: {'num_leaves': 22, 'min_child_samples': 223}. Best is trial 0 with value: 0.4489989451354644.

Trial   3 | Validation MSE: 0.450317 | Unseen Pearson: 0.7396 | Unseen Spearman: 0.7284

[I 2026-07-15 21:32:52,382] Trial 4 finished with value: 0.45120158316024217 and parameters: {'num_leaves': 157, 'min_child_samples': 184}. Best is trial 0 with value: 0.4489989451354644.

Trial   4 | Validation MSE: 0.451202 | Unseen Pearson: 0.7403 | Unseen Spearman: 0.7283

[I 2026-07-15 21:33:07,953] Trial 5 finished with value: 0.45659468002316683 and parameters: {'num_leaves': 13, 'min_child_samples': 249}. Best is trial 0 with value: 0.4489989451354644.

Trial   5 | Validation MSE: 0.456595 | Unseen Pearson: 0.7326 | Unseen Spearman: 0.7215

[I 2026-07-15 21:34:43,343] Trial 6 finished with value: 0.44975668414627157 and parameters: {'num_leaves': 215, 'min_child_samples': 60}. Best is trial 0 with value: 0.4489989451354644.

Trial   6 | Validation MSE: 0.449757 | Unseen Pearson: 0.7407 | Unseen Spearman: 0.7271

[I 2026-07-15 21:35:13,672] Trial 7 finished with value: 0.44913132334022865 and parameters: {'num_leaves': 53, 'min_child_samples': 53}. Best is trial 0 with value: 0.4489989451354644.

Trial   7 | Validation MSE: 0.449131 | Unseen Pearson: 0.7406 | Unseen Spearman: 0.7270

[I 2026-07-15 21:36:02,249] Trial 8 finished with value: 0.44963697461433194 and parameters: {'num_leaves': 83, 'min_child_samples': 138}. Best is trial 0 with value: 0.4489989451354644.

Trial   8 | Validation MSE: 0.449637 | Unseen Pearson: 0.7435 | Unseen Spearman: 0.7312

[I 2026-07-15 21:37:03,087] Trial 9 finished with value: 0.4464799374160952 and parameters: {'num_leaves': 115, 'min_child_samples': 80}. Best is trial 9 with value: 0.4464799374160952.

Trial   9 | Validation MSE: 0.446480 | Unseen Pearson: 0.7444 | Unseen Spearman: 0.7312

[I 2026-07-15 21:38:29,299] Trial 10 finished with value: 0.4572849532512103 and parameters: {'num_leaves': 245, 'min_child_samples': 9}. Best is trial 9 with value: 0.4464799374160952.

Trial  10 | Validation MSE: 0.457285 | Unseen Pearson: 0.7357 | Unseen Spearman: 0.7233

[I 2026-07-15 21:39:24,422] Trial 11 finished with value: 0.4469804810048774 and parameters: {'num_leaves': 107, 'min_child_samples': 94}. Best is trial 9 with value: 0.4464799374160952.

Trial  11 | Validation MSE: 0.446980 | Unseen Pearson: 0.7440 | Unseen Spearman: 0.7312

[I 2026-07-15 21:40:17,315] Trial 12 finished with value: 0.450685385969513 and parameters: {'num_leaves': 129, 'min_child_samples': 106}. Best is trial 9 with value: 0.4464799374160952.

Trial  12 | Validation MSE: 0.450685 | Unseen Pearson: 0.7402 | Unseen Spearman: 0.7267

[I 2026-07-15 21:41:38,291] Trial 13 finished with value: 0.4458224167976793 and parameters: {'num_leaves': 135, 'min_child_samples': 96}. Best is trial 13 with value: 0.4458224167976793.

Trial  13 | Validation MSE: 0.445822 | Unseen Pearson: 0.7434 | Unseen Spearman: 0.7304

[I 2026-07-15 21:42:31,785] Trial 14 finished with value: 0.4519036006899071 and parameters: {'num_leaves': 150, 'min_child_samples': 101}. Best is trial 13 with value: 0.4458224167976793.

Trial  14 | Validation MSE: 0.451904 | Unseen Pearson: 0.7393 | Unseen Spearman: 0.7263

[I 2026-07-15 21:43:48,137] Trial 15 finished with value: 0.4454243692274297 and parameters: {'num_leaves': 169, 'min_child_samples': 80}. Best is trial 15 with value: 0.4454243692274297.

Trial  15 | Validation MSE: 0.445424 | Unseen Pearson: 0.7417 | Unseen Spearman: 0.7288

[I 2026-07-15 21:44:37,703] Trial 16 finished with value: 0.4509339024198687 and parameters: {'num_leaves': 184, 'min_child_samples': 135}. Best is trial 15 with value: 0.4454243692274297.

Trial  16 | Validation MSE: 0.450934 | Unseen Pearson: 0.7400 | Unseen Spearman: 0.7270

[I 2026-07-15 21:45:55,623] Trial 17 finished with value: 0.45123512263731513 and parameters: {'num_leaves': 175, 'min_child_samples': 16}. Best is trial 15 with value: 0.4454243692274297.

Trial  17 | Validation MSE: 0.451235 | Unseen Pearson: 0.7390 | Unseen Spearman: 0.7255

[I 2026-07-15 21:47:00,157] Trial 18 finished with value: 0.44898311235723326 and parameters: {'num_leaves': 218, 'min_child_samples': 128}. Best is trial 15 with value: 0.4454243692274297.

Trial  18 | Validation MSE: 0.448983 | Unseen Pearson: 0.7431 | Unseen Spearman: 0.7303

[I 2026-07-15 21:47:43,041] Trial 19 finished with value: 0.45219560006431986 and parameters: {'num_leaves': 147, 'min_child_samples': 182}. Best is trial 15 with value: 0.4454243692274297.

Trial  19 | Validation MSE: 0.452196 | Unseen Pearson: 0.7396 | Unseen Spearman: 0.7275

[I 2026-07-15 21:48:19,633] Trial 20 finished with value: 0.44992989920766446 and parameters: {'num_leaves': 71, 'min_child_samples': 69}. Best is trial 15 with value: 0.4454243692274297.

Trial  20 | Validation MSE: 0.449930 | Unseen Pearson: 0.7399 | Unseen Spearman: 0.7261

[I 2026-07-15 21:49:13,427] Trial 21 finished with value: 0.448950395044474 and parameters: {'num_leaves': 124, 'min_child_samples': 82}. Best is trial 15 with value: 0.4454243692274297.

Trial  21 | Validation MSE: 0.448950 | Unseen Pearson: 0.7416 | Unseen Spearman: 0.7281

[I 2026-07-15 21:50:30,551] Trial 22 finished with value: 0.4444389299265702 and parameters: {'num_leaves': 112, 'min_child_samples': 113}. Best is trial 22 with value: 0.4444389299265702.

Trial  22 | Validation MSE: 0.444439 | Unseen Pearson: 0.7444 | Unseen Spearman: 0.7315

[I 2026-07-15 21:51:28,695] Trial 23 finished with value: 0.4483097296742191 and parameters: {'num_leaves': 136, 'min_child_samples': 121}. Best is trial 22 with value: 0.4444389299265702.

Trial  23 | Validation MSE: 0.448310 | Unseen Pearson: 0.7427 | Unseen Spearman: 0.7300

[I 2026-07-15 21:53:00,575] Trial 24 finished with value: 0.4469091088552979 and parameters: {'num_leaves': 168, 'min_child_samples': 35}. Best is trial 22 with value: 0.4444389299265702.

Trial  24 | Validation MSE: 0.446909 | Unseen Pearson: 0.7408 | Unseen Spearman: 0.7272

[I 2026-07-15 21:53:49,598] Trial 25 finished with value: 0.4516043770208047 and parameters: {'num_leaves': 96, 'min_child_samples': 160}. Best is trial 22 with value: 0.4444389299265702.

Trial  25 | Validation MSE: 0.451604 | Unseen Pearson: 0.7411 | Unseen Spearman: 0.7291

[I 2026-07-15 21:54:29,253] Trial 26 finished with value: 0.45259904884261665 and parameters: {'num_leaves': 78, 'min_child_samples': 108}. Best is trial 22 with value: 0.4444389299265702.

Trial  26 | Validation MSE: 0.452599 | Unseen Pearson: 0.7392 | Unseen Spearman: 0.7260

[I 2026-07-15 21:55:38,706] Trial 27 finished with value: 0.45065395697388333 and parameters: {'num_leaves': 209, 'min_child_samples': 85}. Best is trial 22 with value: 0.4444389299265702.

Trial  27 | Validation MSE: 0.450654 | Unseen Pearson: 0.7397 | Unseen Spearman: 0.7268

[I 2026-07-15 21:57:16,484] Trial 28 finished with value: 0.44923788840318607 and parameters: {'num_leaves': 198, 'min_child_samples': 34}. Best is trial 22 with value: 0.4444389299265702.

Trial  28 | Validation MSE: 0.449238 | Unseen Pearson: 0.7402 | Unseen Spearman: 0.7265

[I 2026-07-15 21:57:52,313] Trial 29 finished with value: 0.44834279303990926 and parameters: {'num_leaves': 96, 'min_child_samples': 152}. Best is trial 22 with value: 0.4444389299265702.

Trial  29 | Validation MSE: 0.448343 | Unseen Pearson: 0.7414 | Unseen Spearman: 0.7290

[I 2026-07-15 21:58:53,489] Trial 30 finished with value: 0.4509400310498448 and parameters: {'num_leaves': 246, 'min_child_samples': 70}. Best is trial 22 with value: 0.4444389299265702.

Trial  30 | Validation MSE: 0.450940 | Unseen Pearson: 0.7393 | Unseen Spearman: 0.7266

[I 2026-07-15 21:59:27,661] Trial 31 finished with value: 0.4469757772515694 and parameters: {'num_leaves': 117, 'min_child_samples': 79}. Best is trial 22 with value: 0.4444389299265702.

Trial  31 | Validation MSE: 0.446976 | Unseen Pearson: 0.7430 | Unseen Spearman: 0.7298

[I 2026-07-15 22:00:00,964] Trial 32 finished with value: 0.4516501386119537 and parameters: {'num_leaves': 138, 'min_child_samples': 114}. Best is trial 22 with value: 0.4444389299265702.

Trial  32 | Validation MSE: 0.451650 | Unseen Pearson: 0.7414 | Unseen Spearman: 0.7284

[I 2026-07-15 22:00:47,404] Trial 33 finished with value: 0.4465443153646667 and parameters: {'num_leaves': 161, 'min_child_samples': 93}. Best is trial 22 with value: 0.4444389299265702.

Trial  33 | Validation MSE: 0.446544 | Unseen Pearson: 0.7416 | Unseen Spearman: 0.7284

[I 2026-07-15 22:01:16,569] Trial 34 finished with value: 0.4525493939016389 and parameters: {'num_leaves': 110, 'min_child_samples': 45}. Best is trial 22 with value: 0.4444389299265702.

Trial  34 | Validation MSE: 0.452549 | Unseen Pearson: 0.7425 | Unseen Spearman: 0.7288

[I 2026-07-15 22:02:01,109] Trial 35 finished with value: 0.4468992318358485 and parameters: {'num_leaves': 141, 'min_child_samples': 71}. Best is trial 22 with value: 0.4444389299265702.

Trial  35 | Validation MSE: 0.446899 | Unseen Pearson: 0.7421 | Unseen Spearman: 0.7285

[I 2026-07-15 22:02:18,459] Trial 36 finished with value: 0.4520722144324751 and parameters: {'num_leaves': 43, 'min_child_samples': 147}. Best is trial 22 with value: 0.4444389299265702.

Trial  36 | Validation MSE: 0.452072 | Unseen Pearson: 0.7405 | Unseen Spearman: 0.7287

[I 2026-07-15 22:02:49,675] Trial 37 finished with value: 0.4489547707358582 and parameters: {'num_leaves': 92, 'min_child_samples': 167}. Best is trial 22 with value: 0.4444389299265702.

Trial  37 | Validation MSE: 0.448955 | Unseen Pearson: 0.7434 | Unseen Spearman: 0.7313

[I 2026-07-15 22:03:16,532] Trial 38 finished with value: 0.4470329406629988 and parameters: {'num_leaves': 178, 'min_child_samples': 216}. Best is trial 22 with value: 0.4444389299265702.

Trial  38 | Validation MSE: 0.447033 | Unseen Pearson: 0.7412 | Unseen Spearman: 0.7293

[I 2026-07-15 22:03:49,101] Trial 39 finished with value: 0.44624784539737666 and parameters: {'num_leaves': 119, 'min_child_samples': 60}. Best is trial 22 with value: 0.4444389299265702.

Trial  39 | Validation MSE: 0.446248 | Unseen Pearson: 0.7420 | Unseen Spearman: 0.7279

[I 2026-07-15 22:04:33,994] Trial 40 finished with value: 0.4481248383625274 and parameters: {'num_leaves': 162, 'min_child_samples': 44}. Best is trial 22 with value: 0.4444389299265702.

Trial  40 | Validation MSE: 0.448125 | Unseen Pearson: 0.7410 | Unseen Spearman: 0.7268

[I 2026-07-15 22:05:07,173] Trial 41 finished with value: 0.44957368218973637 and parameters: {'num_leaves': 119, 'min_child_samples': 59}. Best is trial 22 with value: 0.4444389299265702.

Trial  41 | Validation MSE: 0.449574 | Unseen Pearson: 0.7408 | Unseen Spearman: 0.7271

[I 2026-07-15 22:05:48,407] Trial 42 finished with value: 0.44520848839153854 and parameters: {'num_leaves': 129, 'min_child_samples': 94}. Best is trial 22 with value: 0.4444389299265702.

Trial  42 | Validation MSE: 0.445208 | Unseen Pearson: 0.7439 | Unseen Spearman: 0.7305

[I 2026-07-15 22:06:26,546] Trial 43 finished with value: 0.4488284536534559 and parameters: {'num_leaves': 129, 'min_child_samples': 96}. Best is trial 22 with value: 0.4444389299265702.

Trial  43 | Validation MSE: 0.448828 | Unseen Pearson: 0.7416 | Unseen Spearman: 0.7287

[I 2026-07-15 22:06:55,450] Trial 44 finished with value: 0.44609115902646523 and parameters: {'num_leaves': 59, 'min_child_samples': 117}. Best is trial 22 with value: 0.4444389299265702.

Trial  44 | Validation MSE: 0.446091 | Unseen Pearson: 0.7433 | Unseen Spearman: 0.7305

[I 2026-07-15 22:07:17,653] Trial 45 finished with value: 0.4499833199621479 and parameters: {'num_leaves': 51, 'min_child_samples': 116}. Best is trial 22 with value: 0.4444389299265702.

Trial  45 | Validation MSE: 0.449983 | Unseen Pearson: 0.7412 | Unseen Spearman: 0.7284

[I 2026-07-15 22:07:30,125] Trial 46 finished with value: 0.45447166509224507 and parameters: {'num_leaves': 27, 'min_child_samples': 120}. Best is trial 22 with value: 0.4444389299265702.

Trial  46 | Validation MSE: 0.454472 | Unseen Pearson: 0.7376 | Unseen Spearman: 0.7253

[I 2026-07-15 22:07:49,301] Trial 47 finished with value: 0.4525470603075086 and parameters: {'num_leaves': 67, 'min_child_samples': 141}. Best is trial 22 with value: 0.4444389299265702.

Trial  47 | Validation MSE: 0.452547 | Unseen Pearson: 0.7391 | Unseen Spearman: 0.7268

[I 2026-07-15 22:08:24,282] Trial 48 finished with value: 0.44898311235723326 and parameters: {'num_leaves': 150, 'min_child_samples': 128}. Best is trial 22 with value: 0.4444389299265702.

Trial  48 | Validation MSE: 0.448983 | Unseen Pearson: 0.7431 | Unseen Spearman: 0.7303

[I 2026-07-15 22:08:37,110] Trial 49 finished with value: 0.45344858748522543 and parameters: {'num_leaves': 24, 'min_child_samples': 102}. Best is trial 22 with value: 0.4444389299265702.

Trial  49 | Validation MSE: 0.453449 | Unseen Pearson: 0.7380 | Unseen Spearman: 0.7257

[I 2026-07-15 22:09:05,381] Trial 50 finished with value: 0.44562786697835466 and parameters: {'num_leaves': 85, 'min_child_samples': 85}. Best is trial 22 with value: 0.4444389299265702.

Trial  50 | Validation MSE: 0.445628 | Unseen Pearson: 0.7431 | Unseen Spearman: 0.7298

[I 2026-07-15 22:09:24,729] Trial 51 finished with value: 0.4508910072745893 and parameters: {'num_leaves': 64, 'min_child_samples': 91}. Best is trial 22 with value: 0.4444389299265702.

Trial  51 | Validation MSE: 0.450891 | Unseen Pearson: 0.7410 | Unseen Spearman: 0.7276

[I 2026-07-15 22:09:48,742] Trial 52 finished with value: 0.450703792763836 and parameters: {'num_leaves': 83, 'min_child_samples': 109}. Best is trial 22 with value: 0.4444389299265702.

Trial  52 | Validation MSE: 0.450704 | Unseen Pearson: 0.7420 | Unseen Spearman: 0.7289

[I 2026-07-15 22:10:16,721] Trial 53 finished with value: 0.4477754223031302 and parameters: {'num_leaves': 103, 'min_child_samples': 75}. Best is trial 22 with value: 0.4444389299265702.

Trial  53 | Validation MSE: 0.447775 | Unseen Pearson: 0.7420 | Unseen Spearman: 0.7282

[I 2026-07-15 22:10:31,558] Trial 54 finished with value: 0.4517249949744262 and parameters: {'num_leaves': 33, 'min_child_samples': 125}. Best is trial 22 with value: 0.4444389299265702.

Trial  54 | Validation MSE: 0.451725 | Unseen Pearson: 0.7406 | Unseen Spearman: 0.7282

[I 2026-07-15 22:10:58,049] Trial 55 finished with value: 0.44759702086111547 and parameters: {'num_leaves': 86, 'min_child_samples': 87}. Best is trial 22 with value: 0.4444389299265702.

Trial  55 | Validation MSE: 0.447597 | Unseen Pearson: 0.7423 | Unseen Spearman: 0.7291

[I 2026-07-15 22:11:33,155] Trial 56 finished with value: 0.4470665117830535 and parameters: {'num_leaves': 131, 'min_child_samples': 100}. Best is trial 22 with value: 0.4444389299265702.

Trial  56 | Validation MSE: 0.447067 | Unseen Pearson: 0.7417 | Unseen Spearman: 0.7287

[I 2026-07-15 22:11:40,970] Trial 57 finished with value: 0.4668297171603778 and parameters: {'num_leaves': 11, 'min_child_samples': 63}. Best is trial 22 with value: 0.4444389299265702.

Trial  57 | Validation MSE: 0.466830 | Unseen Pearson: 0.7271 | Unseen Spearman: 0.7137

[I 2026-07-15 22:12:00,025] Trial 58 finished with value: 0.4492870957667561 and parameters: {'num_leaves': 59, 'min_child_samples': 130}. Best is trial 22 with value: 0.4444389299265702.

Trial  58 | Validation MSE: 0.449287 | Unseen Pearson: 0.7417 | Unseen Spearman: 0.7290

[I 2026-07-15 22:12:28,655] Trial 59 finished with value: 0.44825464219420885 and parameters: {'num_leaves': 73, 'min_child_samples': 110}. Best is trial 22 with value: 0.4444389299265702.

Trial  59 | Validation MSE: 0.448255 | Unseen Pearson: 0.7427 | Unseen Spearman: 0.7296

[I 2026-07-15 22:13:11,688] Trial 60 finished with value: 0.449878435082208 and parameters: {'num_leaves': 190, 'min_child_samples': 84}. Best is trial 22 with value: 0.4444389299265702.

Trial  60 | Validation MSE: 0.449878 | Unseen Pearson: 0.7404 | Unseen Spearman: 0.7271

[I 2026-07-15 22:13:43,347] Trial 61 finished with value: 0.4502656979162012 and parameters: {'num_leaves': 108, 'min_child_samples': 52}. Best is trial 22 with value: 0.4444389299265702.

Trial  61 | Validation MSE: 0.450266 | Unseen Pearson: 0.7416 | Unseen Spearman: 0.7279

[I 2026-07-15 22:14:20,025] Trial 62 finished with value: 0.44736402967499106 and parameters: {'num_leaves': 121, 'min_child_samples': 65}. Best is trial 22 with value: 0.4444389299265702.

Trial  62 | Validation MSE: 0.447364 | Unseen Pearson: 0.7433 | Unseen Spearman: 0.7300

[I 2026-07-15 22:14:57,659] Trial 63 finished with value: 0.45156311774894237 and parameters: {'num_leaves': 146, 'min_child_samples': 31}. Best is trial 22 with value: 0.4444389299265702.

Trial  63 | Validation MSE: 0.451563 | Unseen Pearson: 0.7398 | Unseen Spearman: 0.7261

[I 2026-07-15 22:15:24,116] Trial 64 finished with value: 0.4494176726211633 and parameters: {'num_leaves': 90, 'min_child_samples': 54}. Best is trial 22 with value: 0.4444389299265702.

Trial  64 | Validation MSE: 0.449418 | Unseen Pearson: 0.7414 | Unseen Spearman: 0.7279

[I 2026-07-15 22:15:52,689] Trial 65 finished with value: 0.44950229159464733 and parameters: {'num_leaves': 103, 'min_child_samples': 102}. Best is trial 22 with value: 0.4444389299265702.

Trial  65 | Validation MSE: 0.449502 | Unseen Pearson: 0.7406 | Unseen Spearman: 0.7267

[I 2026-07-15 22:16:31,471] Trial 66 finished with value: 0.447504640348242 and parameters: {'num_leaves': 113, 'min_child_samples': 74}. Best is trial 22 with value: 0.4444389299265702.

Trial  66 | Validation MSE: 0.447505 | Unseen Pearson: 0.7423 | Unseen Spearman: 0.7290

[I 2026-07-15 22:17:09,825] Trial 67 finished with value: 0.4486533170270965 and parameters: {'num_leaves': 127, 'min_child_samples': 94}. Best is trial 22 with value: 0.4444389299265702.

Trial  67 | Validation MSE: 0.448653 | Unseen Pearson: 0.7418 | Unseen Spearman: 0.7282

[I 2026-07-15 22:17:54,802] Trial 68 finished with value: 0.4468470572079135 and parameters: {'num_leaves': 156, 'min_child_samples': 79}. Best is trial 22 with value: 0.4444389299265702.

Trial  68 | Validation MSE: 0.446847 | Unseen Pearson: 0.7421 | Unseen Spearman: 0.7292

[I 2026-07-15 22:18:30,718] Trial 69 finished with value: 0.44763533755801765 and parameters: {'num_leaves': 229, 'min_child_samples': 137}. Best is trial 22 with value: 0.4444389299265702.

Trial  69 | Validation MSE: 0.447635 | Unseen Pearson: 0.7427 | Unseen Spearman: 0.7297

[I 2026-07-15 22:18:53,119] Trial 70 finished with value: 0.44856144366720413 and parameters: {'num_leaves': 76, 'min_child_samples': 117}. Best is trial 22 with value: 0.4444389299265702.

Trial  70 | Validation MSE: 0.448561 | Unseen Pearson: 0.7413 | Unseen Spearman: 0.7282

[I 2026-07-15 22:19:24,977] Trial 71 finished with value: 0.4466595753501883 and parameters: {'num_leaves': 132, 'min_child_samples': 87}. Best is trial 22 with value: 0.4444389299265702.

Trial  71 | Validation MSE: 0.446660 | Unseen Pearson: 0.7416 | Unseen Spearman: 0.7282

[I 2026-07-15 22:19:48,989] Trial 72 finished with value: 0.448868547323702 and parameters: {'num_leaves': 98, 'min_child_samples': 80}. Best is trial 22 with value: 0.4444389299265702.

Trial  72 | Validation MSE: 0.448869 | Unseen Pearson: 0.7411 | Unseen Spearman: 0.7280

[I 2026-07-15 22:20:21,384] Trial 73 finished with value: 0.4446656348270221 and parameters: {'num_leaves': 115, 'min_child_samples': 98}. Best is trial 22 with value: 0.4444389299265702.

Trial  73 | Validation MSE: 0.444666 | Unseen Pearson: 0.7439 | Unseen Spearman: 0.7307

[I 2026-07-15 22:20:56,409] Trial 74 finished with value: 0.4475637681110072 and parameters: {'num_leaves': 140, 'min_child_samples': 106}. Best is trial 22 with value: 0.4444389299265702.

Trial  74 | Validation MSE: 0.447564 | Unseen Pearson: 0.7424 | Unseen Spearman: 0.7295

[I 2026-07-15 22:21:24,319] Trial 75 finished with value: 0.4495214297247264 and parameters: {'num_leaves': 116, 'min_child_samples': 97}. Best is trial 22 with value: 0.4444389299265702.

Trial  75 | Validation MSE: 0.449521 | Unseen Pearson: 0.7426 | Unseen Spearman: 0.7295

[I 2026-07-15 22:22:07,034] Trial 76 finished with value: 0.4460967452364414 and parameters: {'num_leaves': 167, 'min_child_samples': 113}. Best is trial 22 with value: 0.4444389299265702.

Trial  76 | Validation MSE: 0.446097 | Unseen Pearson: 0.7422 | Unseen Spearman: 0.7290

[I 2026-07-15 22:22:57,301] Trial 77 finished with value: 0.4460967452364414 and parameters: {'num_leaves': 170, 'min_child_samples': 113}. Best is trial 22 with value: 0.4444389299265702.

Trial  77 | Validation MSE: 0.446097 | Unseen Pearson: 0.7422 | Unseen Spearman: 0.7290

[I 2026-07-15 22:23:27,779] Trial 78 finished with value: 0.4522209932114936 and parameters: {'num_leaves': 183, 'min_child_samples': 145}. Best is trial 22 with value: 0.4444389299265702.

Trial  78 | Validation MSE: 0.452221 | Unseen Pearson: 0.7414 | Unseen Spearman: 0.7293

[I 2026-07-15 22:24:08,096] Trial 79 finished with value: 0.44742311644564503 and parameters: {'num_leaves': 196, 'min_child_samples': 123}. Best is trial 22 with value: 0.4444389299265702.

Trial  79 | Validation MSE: 0.447423 | Unseen Pearson: 0.7448 | Unseen Spearman: 0.7321

[I 2026-07-15 22:24:48,781] Trial 80 finished with value: 0.4487631609874125 and parameters: {'num_leaves': 144, 'min_child_samples': 133}. Best is trial 22 with value: 0.4444389299265702.

Trial  80 | Validation MSE: 0.448763 | Unseen Pearson: 0.7435 | Unseen Spearman: 0.7305

[I 2026-07-15 22:25:28,608] Trial 81 finished with value: 0.4460967452364414 and parameters: {'num_leaves': 177, 'min_child_samples': 113}. Best is trial 22 with value: 0.4444389299265702.

Trial  81 | Validation MSE: 0.446097 | Unseen Pearson: 0.7422 | Unseen Spearman: 0.7290

[I 2026-07-15 22:26:08,323] Trial 82 finished with value: 0.4490296062029117 and parameters: {'num_leaves': 158, 'min_child_samples': 90}. Best is trial 22 with value: 0.4444389299265702.

Trial  82 | Validation MSE: 0.449030 | Unseen Pearson: 0.7410 | Unseen Spearman: 0.7278

[I 2026-07-15 22:26:50,114] Trial 83 finished with value: 0.44573753914675424 and parameters: {'num_leaves': 168, 'min_child_samples': 103}. Best is trial 22 with value: 0.4444389299265702.

Trial  83 | Validation MSE: 0.445738 | Unseen Pearson: 0.7428 | Unseen Spearman: 0.7302

[I 2026-07-15 22:27:30,568] Trial 84 finished with value: 0.4491420048473587 and parameters: {'num_leaves': 166, 'min_child_samples': 105}. Best is trial 22 with value: 0.4444389299265702.

Trial  84 | Validation MSE: 0.449142 | Unseen Pearson: 0.7425 | Unseen Spearman: 0.7293

[I 2026-07-15 22:28:21,572] Trial 85 finished with value: 0.4467938245439754 and parameters: {'num_leaves': 154, 'min_child_samples': 99}. Best is trial 22 with value: 0.4444389299265702.

Trial  85 | Validation MSE: 0.446794 | Unseen Pearson: 0.7429 | Unseen Spearman: 0.7305

[I 2026-07-15 22:28:53,583] Trial 86 finished with value: 0.45024993772966154 and parameters: {'num_leaves': 135, 'min_child_samples': 119}. Best is trial 22 with value: 0.4444389299265702.

Trial  86 | Validation MSE: 0.450250 | Unseen Pearson: 0.7403 | Unseen Spearman: 0.7276

[I 2026-07-15 22:29:13,374] Trial 87 finished with value: 0.4474363144062589 and parameters: {'num_leaves': 45, 'min_child_samples': 92}. Best is trial 22 with value: 0.4444389299265702.

Trial  87 | Validation MSE: 0.447436 | Unseen Pearson: 0.7421 | Unseen Spearman: 0.7289

[I 2026-07-15 22:29:51,351] Trial 88 finished with value: 0.4494355124361887 and parameters: {'num_leaves': 172, 'min_child_samples': 107}. Best is trial 22 with value: 0.4444389299265702.

Trial  88 | Validation MSE: 0.449436 | Unseen Pearson: 0.7419 | Unseen Spearman: 0.7291

[I 2026-07-15 22:30:28,136] Trial 89 finished with value: 0.4492318394493187 and parameters: {'num_leaves': 165, 'min_child_samples': 77}. Best is trial 22 with value: 0.4444389299265702.

Trial  89 | Validation MSE: 0.449232 | Unseen Pearson: 0.7395 | Unseen Spearman: 0.7261

[I 2026-07-15 22:31:25,266] Trial 90 finished with value: 0.4491624911571869 and parameters: {'num_leaves': 206, 'min_child_samples': 70}. Best is trial 22 with value: 0.4444389299265702.

Trial  90 | Validation MSE: 0.449162 | Unseen Pearson: 0.7396 | Unseen Spearman: 0.7266

[I 2026-07-15 22:32:04,611] Trial 91 finished with value: 0.4460967452364414 and parameters: {'num_leaves': 169, 'min_child_samples': 113}. Best is trial 22 with value: 0.4444389299265702.

Trial  91 | Validation MSE: 0.446097 | Unseen Pearson: 0.7422 | Unseen Spearman: 0.7290

[I 2026-07-15 22:32:29,748] Trial 92 finished with value: 0.44663554514599235 and parameters: {'num_leaves': 185, 'min_child_samples': 238}. Best is trial 22 with value: 0.4444389299265702.

Trial  92 | Validation MSE: 0.446636 | Unseen Pearson: 0.7422 | Unseen Spearman: 0.7312

[I 2026-07-15 22:33:01,152] Trial 93 finished with value: 0.4516598451054839 and parameters: {'num_leaves': 152, 'min_child_samples': 124}. Best is trial 22 with value: 0.4444389299265702.

Trial  93 | Validation MSE: 0.451660 | Unseen Pearson: 0.7425 | Unseen Spearman: 0.7297

[I 2026-07-15 22:33:30,090] Trial 94 finished with value: 0.4485011768919659 and parameters: {'num_leaves': 126, 'min_child_samples': 84}. Best is trial 22 with value: 0.4444389299265702.

Trial  94 | Validation MSE: 0.448501 | Unseen Pearson: 0.7419 | Unseen Spearman: 0.7289

[I 2026-07-15 22:34:09,248] Trial 95 finished with value: 0.4490393301676793 and parameters: {'num_leaves': 173, 'min_child_samples': 111}. Best is trial 22 with value: 0.4444389299265702.

Trial  95 | Validation MSE: 0.449039 | Unseen Pearson: 0.7424 | Unseen Spearman: 0.7293

[I 2026-07-15 22:34:48,806] Trial 96 finished with value: 0.4486417507309754 and parameters: {'num_leaves': 161, 'min_child_samples': 97}. Best is trial 22 with value: 0.4444389299265702.

Trial  96 | Validation MSE: 0.448642 | Unseen Pearson: 0.7412 | Unseen Spearman: 0.7282

[I 2026-07-15 22:35:12,713] Trial 97 finished with value: 0.45402867702387756 and parameters: {'num_leaves': 181, 'min_child_samples': 131}. Best is trial 22 with value: 0.4444389299265702.

Trial  97 | Validation MSE: 0.454029 | Unseen Pearson: 0.7387 | Unseen Spearman: 0.7258

[I 2026-07-15 22:35:42,005] Trial 98 finished with value: 0.44776881291982173 and parameters: {'num_leaves': 82, 'min_child_samples': 103}. Best is trial 22 with value: 0.4444389299265702.

Trial  98 | Validation MSE: 0.447769 | Unseen Pearson: 0.7433 | Unseen Spearman: 0.7301

[I 2026-07-15 22:36:00,005] Trial 99 finished with value: 0.4512561493672074 and parameters: {'num_leaves': 36, 'min_child_samples': 118}. Best is trial 22 with value: 0.4444389299265702.

Trial  99 | Validation MSE: 0.451256 | Unseen Pearson: 0.7394 | Unseen Spearman: 0.7274

In [13]:
results_df = pd.DataFrame(trial_records).sort_values("trial").reset_index(drop=True)
results_df.to_csv(OUTPUT_DIR / "all_100_trial_metrics.csv", index=False)
results_df["validation_mse"].to_csv(OUTPUT_DIR / "Validation_loss.txt", index=False, header=False)
results_df["unseen_pearson"].to_csv(OUTPUT_DIR / "Unseen_Pearson.txt", index=False, header=False)
results_df["unseen_spearman"].to_csv(OUTPUT_DIR / "Unseen_Spearman.txt", index=False, header=False)

best_trial = study.best_trial.number
best_row = results_df.loc[results_df["trial"] == best_trial].iloc[0]
best_model = trial_models[best_trial]

joblib.dump({
    "model": best_model,
    "tracr": TRACR_FILTER,
    "feature_columns": X_train.columns.tolist(),
    "best_trial": best_trial,
    "best_params": study.best_trial.params,
    "best_iteration": study.best_trial.user_attrs["best_iteration"],
    "validation_mse": float(best_row["validation_mse"]),
    "unseen_pearson": float(best_row["unseen_pearson"]),
    "unseen_spearman": float(best_row["unseen_spearman"]),
}, OUTPUT_DIR / "best_model.joblib")

with open(OUTPUT_DIR / "best_trial_summary.json", "w") as f:
    json.dump({
        "tracr": TRACR_FILTER,
        "best_trial": int(best_trial),
        "best_params": study.best_trial.params,
        "best_iteration": int(study.best_trial.user_attrs["best_iteration"]),
        "validation_mse": float(best_row["validation_mse"]),
        "unseen_pearson": float(best_row["unseen_pearson"]),
        "unseen_spearman": float(best_row["unseen_spearman"]),
    }, f, indent=2)

display(results_df.head())
print("\nBest trial:", best_trial)
print(best_row[["validation_mse", "unseen_pearson", "unseen_spearman"]])
print("Saved to:", OUTPUT_DIR.resolve())

   trial  validation_mse  unseen_pearson  unseen_spearman
0      0        0.448999        0.741577         0.730646
1      1        0.450009        0.742665         0.730547
2      2        0.452618        0.740246         0.726012
3      3        0.450317        0.739615         0.728410
4      4        0.451202        0.740255         0.728280

Best trial: 22
validation_mse     0.444439
unseen_pearson     0.744416
unseen_spearman    0.731454
Name: 22, dtype: float64
Saved to: /Users/zhangjiongyu/CRISPR-modular-deep-learning_backup_copy_revision/Revision_existing_model_comparison/RS3/rs_dev/models/rs3_hsu2013_fixed_split_100_trials