# RS3 sequence model: fixed split, 100 Optuna trials

Run this notebook from the repository's `code` directory.

It follows the repository's own data-loading and feature-generation logic:

- loads datasets named in `../data/processed/train_data_names.csv`;
- uses `dataset_list` from `datasets.py`;
- uses `get_feature_df()` from `core.py`;
- creates one fixed grouped and dataset-stratified split with seed 42;
- uses approximately 64% training, 16% validation, and 20% unseen data;
- runs 100 Optuna trials;
- records only:
  - validation MSE;
  - unseen Pearson correlation;
  - unseen Spearman correlation.

The unseen metrics are calculated for every trial as requested, but Optuna selects trials using validation MSE only.

In [1]:
from pathlib import Path
import json
import warnings

import joblib
import lightgbm as lgb
import numpy as np
import optuna
import pandas as pd

from scipy.stats import pearsonr, spearmanr
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import StratifiedGroupKFold

from datasets import dataset_list
from core import get_feature_df

print("LightGBM version:", lgb.__version__)
print("Optuna version:", optuna.__version__)

/opt/anaconda3/envs/rs_dev_venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

LightGBM version: 4.6.0
Optuna version: 4.9.0

## Configuration

Because this notebook is stored in `rs_dev/code`, repository paths begin with `../`.

The original RS3 notebook uses `learning_rate=0.01`, `n_estimators=5000`, and tunes `num_leaves` and `min_child_samples`. This notebook retains that setup.

In [3]:
# Reproducibility
SPLIT_SEED = 42
OPTUNA_SEED = 42
MODEL_SEED = 42

# Experiment
N_TRIALS = 100
EARLY_STOPPING_ROUNDS = 20

# Paths relative to rs_dev/code
PROCESSED_DIR = Path("../data/processed")
OUTPUT_DIR = Path("../models/rs3_fixed_split_100_trials")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_NAMES_FILE = PROCESSED_DIR / "train_data_names.csv"

assert TRAIN_NAMES_FILE.exists(), f"Missing file: {TRAIN_NAMES_FILE.resolve()}"

print("Output directory:", OUTPUT_DIR.resolve())

Output directory: /Users/zhangjiongyu/rs_dev/models/rs3_fixed_split_100_trials

## Load and harmonize the original RS3 training datasets

The duplicate `Doench2016` line in `train_data_names.csv` does **not** load the dataset twice here. The repository iterates once through `dataset_list` and checks whether each dataset name is present in the list.

In [5]:
train_data_names = pd.read_csv(TRAIN_NAMES_FILE)["name"].dropna().astype(str).tolist()

print("Names listed in train_data_names.csv:")
print(train_data_names)

train_data_list = [ds for ds in dataset_list if ds.name in train_data_names]

print("\nDatasets found in dataset_list:")
print([ds.name for ds in train_data_list])

missing_names = sorted(set(train_data_names) - {ds.name for ds in train_data_list})
if missing_names:
    print("\nWarning: names not found in dataset_list:", missing_names)

for ds in train_data_list:
    ds.load_data()
    ds.set_sgrnas()

Names listed in train_data_names.csv:
['Kim2019_train', 'Doench2014_mouse', 'Doench2014_human', 'Doench2016', 'Wang2014', 'Xiang2021', 'Munoz2016', 'Doench2016']

Datasets found in dataset_list:
['Doench2014_mouse', 'Doench2014_human', 'Doench2016', 'Kim2019_train', 'Wang2014', 'Xiang2021', 'Munoz2016']

In [7]:
sg_df_list = []

for ds in train_data_list:
    sg_df = ds.get_sg_df(include_group=True, include_activity=True).copy()
    sg_df["dataset"] = ds.name
    sg_df["tracr"] = ds.tracr
    sg_df_list.append(sg_df)

# Reproduce the target-group construction used in the repository.
sg_df_groups = (
    pd.concat(sg_df_list, ignore_index=True)
    .groupby("sgRNA Context Sequence", as_index=False)
    .agg(
        n_conditions=("sgRNA Context Sequence", "count"),
        target=(
            "sgRNA Target",
            lambda x: ", ".join(
                sorted({
                    str(s).upper()
                    for s in x
                    if not pd.isna(s) and str(s).strip() != ""
                })
            ),
        ),
    )
)

# Guides without an annotated target become singleton groups.
sg_df_groups["target"] = sg_df_groups.apply(
    lambda row: (
        row["target"]
        if row["target"] != ""
        else row["sgRNA Context Sequence"]
    ),
    axis=1,
)

all_data = (
    pd.concat(sg_df_list, ignore_index=True)
    .merge(
        sg_df_groups[["sgRNA Context Sequence", "target"]],
        how="inner",
        on="sgRNA Context Sequence",
    )
    .sort_values(["dataset", "target"])
    .reset_index(drop=True)
)

required_columns = {
    "sgRNA Context Sequence",
    "sgRNA Activity",
    "dataset",
    "tracr",
    "target",
}
missing_columns = required_columns - set(all_data.columns)
if missing_columns:
    raise ValueError(f"Missing required columns: {sorted(missing_columns)}")

all_data["sgRNA Activity"] = pd.to_numeric(
    all_data["sgRNA Activity"], errors="coerce"
)
all_data = all_data.dropna(
    subset=[
        "sgRNA Context Sequence",
        "sgRNA Activity",
        "dataset",
        "tracr",
        "target",
    ]
).reset_index(drop=True)

print("Combined shape:", all_data.shape)
print("Unique context sequences:", all_data["sgRNA Context Sequence"].nunique())
print("Unique target groups:", all_data["target"].nunique())
print("\nRows per dataset:")
display(all_data["dataset"].value_counts().rename("n").to_frame())
print("\nRows per tracrRNA:")
display(all_data["tracr"].value_counts().rename("n").to_frame())

Combined shape: (51087, 8)
Unique context sequences: 46526
Unique target groups: 20637

Rows per dataset:

                      n
dataset
Munoz2016         21136
Kim2019_train     12832
Xiang2021         11397
Doench2016         2536
Doench2014_mouse   1169
Wang2014           1022
Doench2014_human    995

Rows per tracrRNA:

              n
tracr
Hsu2013   29951
Chen2013  21136

## Create one fixed 64%/16%/20% split

Two nested `StratifiedGroupKFold(n_splits=5)` operations are used:

1. Outer fold: 80% seen and 20% unseen.
2. Inner fold within seen data: 80% training and 20% validation.

Groups are based on `target`, so the same target group cannot occur in multiple subsets. Stratification uses `dataset`, matching the repository's grouped cross-validation principle.

In [9]:
# Outer fixed split: seen versus unseen
outer_splitter = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=SPLIT_SEED,
)

seen_idx, unseen_idx = next(
    outer_splitter.split(
        X=all_data,
        y=all_data["dataset"],
        groups=all_data["target"],
    )
)

seen_data = all_data.iloc[seen_idx].reset_index(drop=True)
unseen_data = all_data.iloc[unseen_idx].reset_index(drop=True)

# Inner fixed split: training versus validation within seen data
inner_splitter = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=SPLIT_SEED,
)

train_idx, validation_idx = next(
    inner_splitter.split(
        X=seen_data,
        y=seen_data["dataset"],
        groups=seen_data["target"],
    )
)

train_data = seen_data.iloc[train_idx].reset_index(drop=True)
validation_data = seen_data.iloc[validation_idx].reset_index(drop=True)

# Leakage checks
train_targets = set(train_data["target"])
validation_targets = set(validation_data["target"])
unseen_targets = set(unseen_data["target"])

assert train_targets.isdisjoint(validation_targets)
assert train_targets.isdisjoint(unseen_targets)
assert validation_targets.isdisjoint(unseen_targets)

split_summary = pd.DataFrame(
    {
        "subset": ["train", "validation", "unseen"],
        "n_rows": [len(train_data), len(validation_data), len(unseen_data)],
        "fraction": [
            len(train_data) / len(all_data),
            len(validation_data) / len(all_data),
            len(unseen_data) / len(all_data),
        ],
        "n_target_groups": [
            train_data["target"].nunique(),
            validation_data["target"].nunique(),
            unseen_data["target"].nunique(),
        ],
    }
)

display(split_summary)

print("Dataset distribution by subset:")
display(
    pd.concat(
        {
            "train": train_data["dataset"].value_counts(normalize=True),
            "validation": validation_data["dataset"].value_counts(normalize=True),
            "unseen": unseen_data["dataset"].value_counts(normalize=True),
        },
        axis=1,
    ).fillna(0)
)

       subset  n_rows  fraction  n_target_groups
0       train   32563  0.637403            13002
1  validation    8498  0.166344             3470
2      unseen   10026  0.196253             4165

Dataset distribution by subset:

                     train  validation    unseen
dataset
Munoz2016         0.440868    0.437279  0.305605
Kim2019_train     0.241593    0.233231  0.297526
Xiang2021         0.219697    0.227348  0.230501
Doench2016        0.049504    0.000000  0.092160
Doench2014_mouse  0.018395    0.057072  0.008478
Wang2014          0.018395    0.025418  0.020646
Doench2014_human  0.011547    0.019652  0.045083

## Generate RS3 sequence features

`get_feature_df()` calls `sglearn.featurize_guides()` and adds tracrRNA indicator features, which is the repository's sequence-feature pipeline.

In [11]:
X_train = get_feature_df(train_data)
X_validation = get_feature_df(validation_data)
X_unseen = get_feature_df(unseen_data)

# Force identical feature order.
X_validation = X_validation.reindex(columns=X_train.columns, fill_value=0)
X_unseen = X_unseen.reindex(columns=X_train.columns, fill_value=0)

y_train = train_data["sgRNA Activity"].to_numpy(dtype=float)
y_validation = validation_data["sgRNA Activity"].to_numpy(dtype=float)
y_unseen = unseen_data["sgRNA Activity"].to_numpy(dtype=float)

print("X_train:", X_train.shape)
print("X_validation:", X_validation.shape)
print("X_unseen:", X_unseen.shape)

assert list(X_train.columns) == list(X_validation.columns)
assert list(X_train.columns) == list(X_unseen.columns)

100%|███████████████████████████████████| 32563/32563 [00:05<00:00, 5963.02it/s]
100%|█████████████████████████████████████| 8498/8498 [00:01<00:00, 5922.02it/s]
100%|███████████████████████████████████| 10026/10026 [00:01<00:00, 6013.07it/s]

X_train: (32563, 632)
X_validation: (8498, 632)
X_unseen: (10026, 632)

## Metric helpers

In [15]:
def safe_pearson(y_true, y_pred):
    y_true = np.asarray(y_true, dtype=float).reshape(-1)
    y_pred = np.asarray(y_pred, dtype=float).reshape(-1)

    if len(y_true) < 2 or np.std(y_true) == 0 or np.std(y_pred) == 0:
        return np.nan

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return float(pearsonr(y_true, y_pred)[0])


def safe_spearman(y_true, y_pred):
    y_true = np.asarray(y_true, dtype=float).reshape(-1)
    y_pred = np.asarray(y_pred, dtype=float).reshape(-1)

    if len(y_true) < 2 or np.std(y_true) == 0 or np.std(y_pred) == 0:
        return np.nan

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return float(spearmanr(y_true, y_pred)[0])

## Run 100 fixed-split Optuna trials

Only two hyperparameters are varied, matching the repository's original optimization:

- `num_leaves`: 8–256
- `min_child_samples`: 8–256

All trials use the exact same training, validation, and unseen subsets. Optuna minimizes validation MSE only.

In [17]:
trial_records = []
trial_models = {}


def objective(trial):
    num_leaves = trial.suggest_int("num_leaves", 8, 256)
    min_child_samples = trial.suggest_int("min_child_samples", 8, 256)

    model = lgb.LGBMRegressor(
        objective="regression",
        random_state=MODEL_SEED,
        n_jobs=-1,
        learning_rate=0.01,
        n_estimators=5000,
        num_leaves=num_leaves,
        min_child_samples=min_child_samples,
        verbosity=-1,
    )

    model.fit(
        X_train,
        y_train,
        eval_set=[(X_validation, y_validation)],
        eval_metric="mse",
        callbacks=[
            lgb.early_stopping(
                stopping_rounds=EARLY_STOPPING_ROUNDS,
                verbose=False,
            )
        ],
    )

    best_iteration = (
        model.best_iteration_
        if model.best_iteration_ is not None
        else model.n_estimators
    )

    validation_predictions = model.predict(
        X_validation,
        num_iteration=best_iteration,
    )
    unseen_predictions = model.predict(
        X_unseen,
        num_iteration=best_iteration,
    )

    validation_mse = float(
        mean_squared_error(y_validation, validation_predictions)
    )
    unseen_pearson = safe_pearson(y_unseen, unseen_predictions)
    unseen_spearman = safe_spearman(y_unseen, unseen_predictions)

    trial.set_user_attr("best_iteration", int(best_iteration))
    trial.set_user_attr("unseen_pearson", unseen_pearson)
    trial.set_user_attr("unseen_spearman", unseen_spearman)

    trial_records.append(
        {
            "trial": trial.number,
            "validation_mse": validation_mse,
            "unseen_pearson": unseen_pearson,
            "unseen_spearman": unseen_spearman,
        }
    )

    # Retain the fitted model so the best trial can be saved directly.
    trial_models[trial.number] = model

    print(
        f"Trial {trial.number:3d} | "
        f"Validation MSE: {validation_mse:.6f} | "
        f"Unseen Pearson: {unseen_pearson:.4f} | "
        f"Unseen Spearman: {unseen_spearman:.4f}"
    )

    return validation_mse


sampler = optuna.samplers.TPESampler(seed=OPTUNA_SEED)

study = optuna.create_study(
    direction="minimize",
    sampler=sampler,
    study_name="rs3_fixed_split_100_trials",
)

study.optimize(objective, n_trials=N_TRIALS)

[I 2026-07-11 17:19:42,260] A new study created in memory with name: rs3_fixed_split_100_trials
[I 2026-07-11 17:20:22,267] Trial 0 finished with value: 0.5649625605349683 and parameters: {'num_leaves': 101, 'min_child_samples': 244}. Best is trial 0 with value: 0.5649625605349683.

Trial   0 | Validation MSE: 0.564963 | Unseen Pearson: 0.6627 | Unseen Spearman: 0.6458

[I 2026-07-11 17:21:02,980] Trial 1 finished with value: 0.5674606755251624 and parameters: {'num_leaves': 190, 'min_child_samples': 157}. Best is trial 0 with value: 0.5649625605349683.

Trial   1 | Validation MSE: 0.567461 | Unseen Pearson: 0.6596 | Unseen Spearman: 0.6425

[I 2026-07-11 17:21:23,441] Trial 2 finished with value: 0.5801804998308076 and parameters: {'num_leaves': 46, 'min_child_samples': 46}. Best is trial 0 with value: 0.5649625605349683.

Trial   2 | Validation MSE: 0.580180 | Unseen Pearson: 0.6527 | Unseen Spearman: 0.6349

[I 2026-07-11 17:21:46,076] Trial 3 finished with value: 0.5703315043442162 and parameters: {'num_leaves': 22, 'min_child_samples': 223}. Best is trial 0 with value: 0.5649625605349683.

Trial   3 | Validation MSE: 0.570332 | Unseen Pearson: 0.6551 | Unseen Spearman: 0.6386

[I 2026-07-11 17:22:24,481] Trial 4 finished with value: 0.5668251282967531 and parameters: {'num_leaves': 157, 'min_child_samples': 184}. Best is trial 0 with value: 0.5649625605349683.

Trial   4 | Validation MSE: 0.566825 | Unseen Pearson: 0.6586 | Unseen Spearman: 0.6418

[I 2026-07-11 17:22:39,227] Trial 5 finished with value: 0.5841023412948847 and parameters: {'num_leaves': 13, 'min_child_samples': 249}. Best is trial 0 with value: 0.5649625605349683.

Trial   5 | Validation MSE: 0.584102 | Unseen Pearson: 0.6472 | Unseen Spearman: 0.6310

[I 2026-07-11 17:23:34,402] Trial 6 finished with value: 0.5696925104372078 and parameters: {'num_leaves': 215, 'min_child_samples': 60}. Best is trial 0 with value: 0.5649625605349683.

Trial   6 | Validation MSE: 0.569693 | Unseen Pearson: 0.6611 | Unseen Spearman: 0.6423

[I 2026-07-11 17:24:03,083] Trial 7 finished with value: 0.5730162443052071 and parameters: {'num_leaves': 53, 'min_child_samples': 53}. Best is trial 0 with value: 0.5649625605349683.

Trial   7 | Validation MSE: 0.573016 | Unseen Pearson: 0.6576 | Unseen Spearman: 0.6398

[I 2026-07-11 17:24:34,326] Trial 8 finished with value: 0.5653736202851238 and parameters: {'num_leaves': 83, 'min_child_samples': 138}. Best is trial 0 with value: 0.5649625605349683.

Trial   8 | Validation MSE: 0.565374 | Unseen Pearson: 0.6605 | Unseen Spearman: 0.6432

[I 2026-07-11 17:25:10,184] Trial 9 finished with value: 0.5691812651039512 and parameters: {'num_leaves': 115, 'min_child_samples': 80}. Best is trial 0 with value: 0.5649625605349683.

Trial   9 | Validation MSE: 0.569181 | Unseen Pearson: 0.6625 | Unseen Spearman: 0.6448

[I 2026-07-11 17:26:01,583] Trial 10 finished with value: 0.5826564825825838 and parameters: {'num_leaves': 244, 'min_child_samples': 9}. Best is trial 0 with value: 0.5649625605349683.

Trial  10 | Validation MSE: 0.582656 | Unseen Pearson: 0.6533 | Unseen Spearman: 0.6352

[I 2026-07-11 17:26:36,645] Trial 11 finished with value: 0.565110745735181 and parameters: {'num_leaves': 107, 'min_child_samples': 126}. Best is trial 0 with value: 0.5649625605349683.

Trial  11 | Validation MSE: 0.565111 | Unseen Pearson: 0.6611 | Unseen Spearman: 0.6437

[I 2026-07-11 17:27:18,412] Trial 12 finished with value: 0.5671236254711348 and parameters: {'num_leaves': 125, 'min_child_samples': 103}. Best is trial 0 with value: 0.5649625605349683.

Trial  12 | Validation MSE: 0.567124 | Unseen Pearson: 0.6632 | Unseen Spearman: 0.6452

[I 2026-07-11 17:27:52,756] Trial 13 finished with value: 0.5660073851592634 and parameters: {'num_leaves': 110, 'min_child_samples': 208}. Best is trial 0 with value: 0.5649625605349683.

Trial  13 | Validation MSE: 0.566007 | Unseen Pearson: 0.6588 | Unseen Spearman: 0.6421

[I 2026-07-11 17:28:40,354] Trial 14 finished with value: 0.5666835710355255 and parameters: {'num_leaves': 158, 'min_child_samples': 134}. Best is trial 0 with value: 0.5649625605349683.

Trial  14 | Validation MSE: 0.566684 | Unseen Pearson: 0.6621 | Unseen Spearman: 0.6451

[I 2026-07-11 17:29:04,402] Trial 15 finished with value: 0.5673117886334997 and parameters: {'num_leaves': 77, 'min_child_samples': 179}. Best is trial 0 with value: 0.5649625605349683.

Trial  15 | Validation MSE: 0.567312 | Unseen Pearson: 0.6578 | Unseen Spearman: 0.6409

[I 2026-07-11 17:29:45,331] Trial 16 finished with value: 0.5640318052802361 and parameters: {'num_leaves': 150, 'min_child_samples': 254}. Best is trial 16 with value: 0.5640318052802361.

Trial  16 | Validation MSE: 0.564032 | Unseen Pearson: 0.6626 | Unseen Spearman: 0.6461

[I 2026-07-11 17:30:25,870] Trial 17 finished with value: 0.5664037457182597 and parameters: {'num_leaves': 159, 'min_child_samples': 249}. Best is trial 16 with value: 0.5640318052802361.

Trial  17 | Validation MSE: 0.566404 | Unseen Pearson: 0.6627 | Unseen Spearman: 0.6460

[I 2026-07-11 17:31:05,885] Trial 18 finished with value: 0.5646152971229974 and parameters: {'num_leaves': 189, 'min_child_samples': 220}. Best is trial 16 with value: 0.5640318052802361.

Trial  18 | Validation MSE: 0.564615 | Unseen Pearson: 0.6607 | Unseen Spearman: 0.6438

[I 2026-07-11 17:31:44,665] Trial 19 finished with value: 0.5658203238653405 and parameters: {'num_leaves': 190, 'min_child_samples': 207}. Best is trial 16 with value: 0.5640318052802361.

Trial  19 | Validation MSE: 0.565820 | Unseen Pearson: 0.6593 | Unseen Spearman: 0.6431

[I 2026-07-11 17:32:19,282] Trial 20 finished with value: 0.56760930910368 and parameters: {'num_leaves': 235, 'min_child_samples': 222}. Best is trial 16 with value: 0.5640318052802361.

Trial  20 | Validation MSE: 0.567609 | Unseen Pearson: 0.6590 | Unseen Spearman: 0.6422

[I 2026-07-11 17:32:56,382] Trial 21 finished with value: 0.5660722076970215 and parameters: {'num_leaves': 139, 'min_child_samples': 246}. Best is trial 16 with value: 0.5640318052802361.

Trial  21 | Validation MSE: 0.566072 | Unseen Pearson: 0.6609 | Unseen Spearman: 0.6443

[I 2026-07-11 17:33:30,899] Trial 22 finished with value: 0.5682626741910775 and parameters: {'num_leaves': 190, 'min_child_samples': 228}. Best is trial 16 with value: 0.5640318052802361.

Trial  22 | Validation MSE: 0.568263 | Unseen Pearson: 0.6586 | Unseen Spearman: 0.6418

[I 2026-07-11 17:34:05,824] Trial 23 finished with value: 0.5654658103391406 and parameters: {'num_leaves': 211, 'min_child_samples': 192}. Best is trial 16 with value: 0.5640318052802361.

Trial  23 | Validation MSE: 0.565466 | Unseen Pearson: 0.6584 | Unseen Spearman: 0.6416

[I 2026-07-11 17:34:40,379] Trial 24 finished with value: 0.5672301962045945 and parameters: {'num_leaves': 140, 'min_child_samples': 255}. Best is trial 16 with value: 0.5640318052802361.

Trial  24 | Validation MSE: 0.567230 | Unseen Pearson: 0.6598 | Unseen Spearman: 0.6428

[I 2026-07-11 17:35:10,804] Trial 25 finished with value: 0.5689937256642138 and parameters: {'num_leaves': 90, 'min_child_samples': 230}. Best is trial 16 with value: 0.5640318052802361.

Trial  25 | Validation MSE: 0.568994 | Unseen Pearson: 0.6594 | Unseen Spearman: 0.6428

[I 2026-07-11 17:35:57,294] Trial 26 finished with value: 0.5633491281433395 and parameters: {'num_leaves': 166, 'min_child_samples': 166}. Best is trial 26 with value: 0.5633491281433395.

Trial  26 | Validation MSE: 0.563349 | Unseen Pearson: 0.6616 | Unseen Spearman: 0.6447

[I 2026-07-11 17:36:40,561] Trial 27 finished with value: 0.5632697280254054 and parameters: {'num_leaves': 172, 'min_child_samples': 161}. Best is trial 27 with value: 0.5632697280254054.

Trial  27 | Validation MSE: 0.563270 | Unseen Pearson: 0.6620 | Unseen Spearman: 0.6451

[I 2026-07-11 17:37:29,775] Trial 28 finished with value: 0.5646949008962812 and parameters: {'num_leaves': 162, 'min_child_samples': 158}. Best is trial 27 with value: 0.5632697280254054.

Trial  28 | Validation MSE: 0.564695 | Unseen Pearson: 0.6618 | Unseen Spearman: 0.6447

[I 2026-07-11 17:38:15,894] Trial 29 finished with value: 0.5633491281433395 and parameters: {'num_leaves': 178, 'min_child_samples': 166}. Best is trial 27 with value: 0.5632697280254054.

Trial  29 | Validation MSE: 0.563349 | Unseen Pearson: 0.6616 | Unseen Spearman: 0.6447

[I 2026-07-11 17:39:01,928] Trial 30 finished with value: 0.5643540244854983 and parameters: {'num_leaves': 173, 'min_child_samples': 162}. Best is trial 27 with value: 0.5632697280254054.

Trial  30 | Validation MSE: 0.564354 | Unseen Pearson: 0.6607 | Unseen Spearman: 0.6436

[I 2026-07-11 17:39:58,312] Trial 31 finished with value: 0.566356554906148 and parameters: {'num_leaves': 207, 'min_child_samples': 112}. Best is trial 27 with value: 0.5632697280254054.

Trial  31 | Validation MSE: 0.566357 | Unseen Pearson: 0.6623 | Unseen Spearman: 0.6449

[I 2026-07-11 17:40:34,800] Trial 32 finished with value: 0.5671877564741853 and parameters: {'num_leaves': 140, 'min_child_samples': 170}. Best is trial 27 with value: 0.5632697280254054.

Trial  32 | Validation MSE: 0.567188 | Unseen Pearson: 0.6597 | Unseen Spearman: 0.6435

[I 2026-07-11 17:41:16,859] Trial 33 finished with value: 0.5678921145436654 and parameters: {'num_leaves': 173, 'min_child_samples': 146}. Best is trial 27 with value: 0.5632697280254054.

Trial  33 | Validation MSE: 0.567892 | Unseen Pearson: 0.6591 | Unseen Spearman: 0.6424

[I 2026-07-11 17:41:55,860] Trial 34 finished with value: 0.5638977149531355 and parameters: {'num_leaves': 141, 'min_child_samples': 202}. Best is trial 27 with value: 0.5632697280254054.

Trial  34 | Validation MSE: 0.563898 | Unseen Pearson: 0.6603 | Unseen Spearman: 0.6435

[I 2026-07-11 17:42:39,231] Trial 35 finished with value: 0.5643493117748094 and parameters: {'num_leaves': 176, 'min_child_samples': 195}. Best is trial 27 with value: 0.5632697280254054.

Trial  35 | Validation MSE: 0.564349 | Unseen Pearson: 0.6597 | Unseen Spearman: 0.6424

[I 2026-07-11 17:43:23,641] Trial 36 finished with value: 0.5641116458707242 and parameters: {'num_leaves': 133, 'min_child_samples': 150}. Best is trial 27 with value: 0.5632697280254054.

Trial  36 | Validation MSE: 0.564112 | Unseen Pearson: 0.6623 | Unseen Spearman: 0.6456

[I 2026-07-11 17:44:13,163] Trial 37 finished with value: 0.5645635166573634 and parameters: {'num_leaves': 224, 'min_child_samples': 172}. Best is trial 27 with value: 0.5632697280254054.

Trial  37 | Validation MSE: 0.564564 | Unseen Pearson: 0.6610 | Unseen Spearman: 0.6440

[I 2026-07-11 17:44:51,580] Trial 38 finished with value: 0.5651863193888644 and parameters: {'num_leaves': 202, 'min_child_samples': 191}. Best is trial 27 with value: 0.5632697280254054.

Trial  38 | Validation MSE: 0.565186 | Unseen Pearson: 0.6593 | Unseen Spearman: 0.6427

[I 2026-07-11 17:45:35,444] Trial 39 finished with value: 0.563347818626683 and parameters: {'num_leaves': 122, 'min_child_samples': 205}. Best is trial 27 with value: 0.5632697280254054.

Trial  39 | Validation MSE: 0.563348 | Unseen Pearson: 0.6616 | Unseen Spearman: 0.6453

[I 2026-07-11 17:46:23,577] Trial 40 finished with value: 0.5614106886949427 and parameters: {'num_leaves': 125, 'min_child_samples': 122}. Best is trial 40 with value: 0.5614106886949427.

Trial  40 | Validation MSE: 0.561411 | Unseen Pearson: 0.6619 | Unseen Spearman: 0.6439

[I 2026-07-11 17:47:00,983] Trial 41 finished with value: 0.5653535825050681 and parameters: {'num_leaves': 97, 'min_child_samples': 115}. Best is trial 40 with value: 0.5614106886949427.

Trial  41 | Validation MSE: 0.565354 | Unseen Pearson: 0.6617 | Unseen Spearman: 0.6437

[I 2026-07-11 17:47:34,664] Trial 42 finished with value: 0.566884742609753 and parameters: {'num_leaves': 124, 'min_child_samples': 166}. Best is trial 40 with value: 0.5614106886949427.

Trial  42 | Validation MSE: 0.566885 | Unseen Pearson: 0.6581 | Unseen Spearman: 0.6412

[I 2026-07-11 17:48:12,635] Trial 43 finished with value: 0.5662142694843326 and parameters: {'num_leaves': 172, 'min_child_samples': 180}. Best is trial 40 with value: 0.5614106886949427.

Trial  43 | Validation MSE: 0.566214 | Unseen Pearson: 0.6601 | Unseen Spearman: 0.6433

[I 2026-07-11 17:48:41,107] Trial 44 finished with value: 0.571431796205777 and parameters: {'num_leaves': 71, 'min_child_samples': 91}. Best is trial 40 with value: 0.5614106886949427.

Trial  44 | Validation MSE: 0.571432 | Unseen Pearson: 0.6592 | Unseen Spearman: 0.6417

[I 2026-07-11 17:49:17,395] Trial 45 finished with value: 0.5670566927329311 and parameters: {'num_leaves': 125, 'min_child_samples': 130}. Best is trial 40 with value: 0.5614106886949427.

Trial  45 | Validation MSE: 0.567057 | Unseen Pearson: 0.6619 | Unseen Spearman: 0.6445

[I 2026-07-11 17:49:46,488] Trial 46 finished with value: 0.5648433541178888 and parameters: {'num_leaves': 58, 'min_child_samples': 145}. Best is trial 40 with value: 0.5614106886949427.

Trial  46 | Validation MSE: 0.564843 | Unseen Pearson: 0.6596 | Unseen Spearman: 0.6425

[I 2026-07-11 17:50:32,814] Trial 47 finished with value: 0.5655370282514083 and parameters: {'num_leaves': 151, 'min_child_samples': 121}. Best is trial 40 with value: 0.5614106886949427.

Trial  47 | Validation MSE: 0.565537 | Unseen Pearson: 0.6627 | Unseen Spearman: 0.6454

[I 2026-07-11 17:50:50,242] Trial 48 finished with value: 0.578692021725225 and parameters: {'num_leaves': 37, 'min_child_samples': 82}. Best is trial 40 with value: 0.5614106886949427.

Trial  48 | Validation MSE: 0.578692 | Unseen Pearson: 0.6518 | Unseen Spearman: 0.6348

[I 2026-07-11 17:51:51,963] Trial 49 finished with value: 0.5750368644936688 and parameters: {'num_leaves': 199, 'min_child_samples': 30}. Best is trial 40 with value: 0.5614106886949427.

Trial  49 | Validation MSE: 0.575037 | Unseen Pearson: 0.6578 | Unseen Spearman: 0.6390

[I 2026-07-11 17:52:27,300] Trial 50 finished with value: 0.5675964863819207 and parameters: {'num_leaves': 116, 'min_child_samples': 139}. Best is trial 40 with value: 0.5614106886949427.

Trial  50 | Validation MSE: 0.567596 | Unseen Pearson: 0.6593 | Unseen Spearman: 0.6420

[I 2026-07-11 17:53:06,779] Trial 51 finished with value: 0.5644342799051972 and parameters: {'num_leaves': 147, 'min_child_samples': 205}. Best is trial 40 with value: 0.5614106886949427.

Trial  51 | Validation MSE: 0.564434 | Unseen Pearson: 0.6601 | Unseen Spearman: 0.6438

[I 2026-07-11 17:53:51,032] Trial 52 finished with value: 0.5637297154637565 and parameters: {'num_leaves': 164, 'min_child_samples': 182}. Best is trial 40 with value: 0.5614106886949427.

Trial  52 | Validation MSE: 0.563730 | Unseen Pearson: 0.6602 | Unseen Spearman: 0.6437

[I 2026-07-11 17:54:35,360] Trial 53 finished with value: 0.5637297154637565 and parameters: {'num_leaves': 165, 'min_child_samples': 182}. Best is trial 40 with value: 0.5614106886949427.

Trial  53 | Validation MSE: 0.563730 | Unseen Pearson: 0.6602 | Unseen Spearman: 0.6437

[I 2026-07-11 17:55:25,948] Trial 54 finished with value: 0.5654837916516794 and parameters: {'num_leaves': 184, 'min_child_samples': 153}. Best is trial 40 with value: 0.5614106886949427.

Trial  54 | Validation MSE: 0.565484 | Unseen Pearson: 0.6619 | Unseen Spearman: 0.6449

[I 2026-07-11 17:56:07,734] Trial 55 finished with value: 0.5645738749053126 and parameters: {'num_leaves': 183, 'min_child_samples': 174}. Best is trial 40 with value: 0.5614106886949427.

Trial  55 | Validation MSE: 0.564574 | Unseen Pearson: 0.6609 | Unseen Spearman: 0.6442

[I 2026-07-11 17:56:54,190] Trial 56 finished with value: 0.5634085009363966 and parameters: {'num_leaves': 256, 'min_child_samples': 189}. Best is trial 40 with value: 0.5614106886949427.

Trial  56 | Validation MSE: 0.563409 | Unseen Pearson: 0.6617 | Unseen Spearman: 0.6450

[I 2026-07-11 17:57:32,413] Trial 57 finished with value: 0.5658477660357629 and parameters: {'num_leaves': 250, 'min_child_samples': 219}. Best is trial 40 with value: 0.5614106886949427.

Trial  57 | Validation MSE: 0.565848 | Unseen Pearson: 0.6588 | Unseen Spearman: 0.6423

[I 2026-07-11 17:58:15,858] Trial 58 finished with value: 0.5632697280254054 and parameters: {'num_leaves': 223, 'min_child_samples': 161}. Best is trial 40 with value: 0.5614106886949427.

Trial  58 | Validation MSE: 0.563270 | Unseen Pearson: 0.6620 | Unseen Spearman: 0.6451

[I 2026-07-11 17:59:19,558] Trial 59 finished with value: 0.5672702973413926 and parameters: {'num_leaves': 230, 'min_child_samples': 103}. Best is trial 40 with value: 0.5614106886949427.

Trial  59 | Validation MSE: 0.567270 | Unseen Pearson: 0.6620 | Unseen Spearman: 0.6438

[I 2026-07-11 18:00:09,973] Trial 60 finished with value: 0.5657753747888293 and parameters: {'num_leaves': 198, 'min_child_samples': 139}. Best is trial 40 with value: 0.5614106886949427.

Trial  60 | Validation MSE: 0.565775 | Unseen Pearson: 0.6616 | Unseen Spearman: 0.6446

[I 2026-07-11 18:00:56,216] Trial 61 finished with value: 0.5643540244854983 and parameters: {'num_leaves': 255, 'min_child_samples': 162}. Best is trial 40 with value: 0.5614106886949427.

Trial  61 | Validation MSE: 0.564354 | Unseen Pearson: 0.6607 | Unseen Spearman: 0.6436

[I 2026-07-11 18:01:51,273] Trial 62 finished with value: 0.5634968407555313 and parameters: {'num_leaves': 219, 'min_child_samples': 158}. Best is trial 40 with value: 0.5614106886949427.

Trial  62 | Validation MSE: 0.563497 | Unseen Pearson: 0.6617 | Unseen Spearman: 0.6449

[I 2026-07-11 18:02:29,666] Trial 63 finished with value: 0.5651863193888644 and parameters: {'num_leaves': 233, 'min_child_samples': 191}. Best is trial 40 with value: 0.5614106886949427.

Trial  63 | Validation MSE: 0.565186 | Unseen Pearson: 0.6593 | Unseen Spearman: 0.6427

[I 2026-07-11 18:03:07,429] Trial 64 finished with value: 0.5645817918577558 and parameters: {'num_leaves': 243, 'min_child_samples': 214}. Best is trial 40 with value: 0.5614106886949427.

Trial  64 | Validation MSE: 0.564582 | Unseen Pearson: 0.6606 | Unseen Spearman: 0.6439

[I 2026-07-11 18:03:40,098] Trial 65 finished with value: 0.5650417138517798 and parameters: {'num_leaves': 101, 'min_child_samples': 198}. Best is trial 40 with value: 0.5614106886949427.

Trial  65 | Validation MSE: 0.565042 | Unseen Pearson: 0.6598 | Unseen Spearman: 0.6432

[I 2026-07-11 18:04:11,886] Trial 66 finished with value: 0.568424960229571 and parameters: {'num_leaves': 244, 'min_child_samples': 234}. Best is trial 40 with value: 0.5614106886949427.

Trial  66 | Validation MSE: 0.568425 | Unseen Pearson: 0.6588 | Unseen Spearman: 0.6422

[I 2026-07-11 18:05:00,464] Trial 67 finished with value: 0.5713398644049992 and parameters: {'num_leaves': 219, 'min_child_samples': 66}. Best is trial 40 with value: 0.5614106886949427.

Trial  67 | Validation MSE: 0.571340 | Unseen Pearson: 0.6600 | Unseen Spearman: 0.6413

[I 2026-07-11 18:05:47,226] Trial 68 finished with value: 0.5627348972818573 and parameters: {'num_leaves': 118, 'min_child_samples': 173}. Best is trial 40 with value: 0.5614106886949427.

Trial  68 | Validation MSE: 0.562735 | Unseen Pearson: 0.6615 | Unseen Spearman: 0.6448

[I 2026-07-11 18:06:23,213] Trial 69 finished with value: 0.5649058055407173 and parameters: {'num_leaves': 105, 'min_child_samples': 174}. Best is trial 40 with value: 0.5614106886949427.

Trial  69 | Validation MSE: 0.564906 | Unseen Pearson: 0.6607 | Unseen Spearman: 0.6435

[I 2026-07-11 18:07:01,485] Trial 70 finished with value: 0.5652951107948884 and parameters: {'num_leaves': 127, 'min_child_samples': 166}. Best is trial 40 with value: 0.5614106886949427.

Trial  70 | Validation MSE: 0.565295 | Unseen Pearson: 0.6611 | Unseen Spearman: 0.6441

[I 2026-07-11 18:07:33,072] Trial 71 finished with value: 0.5677936314275022 and parameters: {'num_leaves': 118, 'min_child_samples': 188}. Best is trial 40 with value: 0.5614106886949427.

Trial  71 | Validation MSE: 0.567794 | Unseen Pearson: 0.6589 | Unseen Spearman: 0.6421

[I 2026-07-11 18:08:06,132] Trial 72 finished with value: 0.5657066279294489 and parameters: {'num_leaves': 95, 'min_child_samples': 155}. Best is trial 40 with value: 0.5614106886949427.

Trial  72 | Validation MSE: 0.565707 | Unseen Pearson: 0.6619 | Unseen Spearman: 0.6444

[I 2026-07-11 18:08:50,637] Trial 73 finished with value: 0.5658694625683188 and parameters: {'num_leaves': 154, 'min_child_samples': 143}. Best is trial 40 with value: 0.5614106886949427.

Trial  73 | Validation MSE: 0.565869 | Unseen Pearson: 0.6612 | Unseen Spearman: 0.6442

[I 2026-07-11 18:09:26,152] Trial 74 finished with value: 0.5656155849335646 and parameters: {'num_leaves': 135, 'min_child_samples': 212}. Best is trial 40 with value: 0.5614106886949427.

Trial  74 | Validation MSE: 0.565616 | Unseen Pearson: 0.6597 | Unseen Spearman: 0.6432

[I 2026-07-11 18:10:03,856] Trial 75 finished with value: 0.5673756624738774 and parameters: {'num_leaves': 210, 'min_child_samples': 186}. Best is trial 40 with value: 0.5614106886949427.

Trial  75 | Validation MSE: 0.567376 | Unseen Pearson: 0.6585 | Unseen Spearman: 0.6415

[I 2026-07-11 18:10:46,459] Trial 76 finished with value: 0.5636909975609873 and parameters: {'num_leaves': 132, 'min_child_samples': 200}. Best is trial 40 with value: 0.5614106886949427.

Trial  76 | Validation MSE: 0.563691 | Unseen Pearson: 0.6616 | Unseen Spearman: 0.6447

[I 2026-07-11 18:11:34,753] Trial 77 finished with value: 0.5638911283290126 and parameters: {'num_leaves': 144, 'min_child_samples': 151}. Best is trial 40 with value: 0.5614106886949427.

Trial  77 | Validation MSE: 0.563891 | Unseen Pearson: 0.6615 | Unseen Spearman: 0.6449

[I 2026-07-11 18:12:15,146] Trial 78 finished with value: 0.5632807849107273 and parameters: {'num_leaves': 87, 'min_child_samples': 128}. Best is trial 40 with value: 0.5614106886949427.

Trial  78 | Validation MSE: 0.563281 | Unseen Pearson: 0.6616 | Unseen Spearman: 0.6442

[I 2026-07-11 18:12:44,609] Trial 79 finished with value: 0.5677863124875904 and parameters: {'num_leaves': 89, 'min_child_samples': 123}. Best is trial 40 with value: 0.5614106886949427.

Trial  79 | Validation MSE: 0.567786 | Unseen Pearson: 0.6596 | Unseen Spearman: 0.6420

[I 2026-07-11 18:13:12,183] Trial 80 finished with value: 0.5697402341253675 and parameters: {'num_leaves': 79, 'min_child_samples': 109}. Best is trial 40 with value: 0.5614106886949427.

Trial  80 | Validation MSE: 0.569740 | Unseen Pearson: 0.6585 | Unseen Spearman: 0.6408

[I 2026-07-11 18:13:52,284] Trial 81 finished with value: 0.5647743987077279 and parameters: {'num_leaves': 112, 'min_child_samples': 133}. Best is trial 40 with value: 0.5614106886949427.

Trial  81 | Validation MSE: 0.564774 | Unseen Pearson: 0.6625 | Unseen Spearman: 0.6450

[I 2026-07-11 18:14:17,110] Trial 82 finished with value: 0.5656684574979703 and parameters: {'num_leaves': 57, 'min_child_samples': 176}. Best is trial 40 with value: 0.5614106886949427.

Trial  82 | Validation MSE: 0.565668 | Unseen Pearson: 0.6578 | Unseen Spearman: 0.6408

[I 2026-07-11 18:15:09,520] Trial 83 finished with value: 0.561796361880533 and parameters: {'num_leaves': 178, 'min_child_samples': 168}. Best is trial 40 with value: 0.5614106886949427.

Trial  83 | Validation MSE: 0.561796 | Unseen Pearson: 0.6617 | Unseen Spearman: 0.6449

[I 2026-07-11 18:15:56,039] Trial 84 finished with value: 0.5633491281433395 and parameters: {'num_leaves': 179, 'min_child_samples': 166}. Best is trial 40 with value: 0.5614106886949427.

Trial  84 | Validation MSE: 0.563349 | Unseen Pearson: 0.6616 | Unseen Spearman: 0.6447

[I 2026-07-11 18:16:42,474] Trial 85 finished with value: 0.5682525113533551 and parameters: {'num_leaves': 168, 'min_child_samples': 129}. Best is trial 40 with value: 0.5614106886949427.

Trial  85 | Validation MSE: 0.568253 | Unseen Pearson: 0.6596 | Unseen Spearman: 0.6425

[I 2026-07-11 18:17:31,458] Trial 86 finished with value: 0.5640445827547882 and parameters: {'num_leaves': 156, 'min_child_samples': 117}. Best is trial 40 with value: 0.5614106886949427.

Trial  86 | Validation MSE: 0.564045 | Unseen Pearson: 0.6626 | Unseen Spearman: 0.6448

[I 2026-07-11 18:18:24,738] Trial 87 finished with value: 0.566485591219723 and parameters: {'num_leaves': 188, 'min_child_samples': 97}. Best is trial 40 with value: 0.5614106886949427.

Trial  87 | Validation MSE: 0.566486 | Unseen Pearson: 0.6633 | Unseen Spearman: 0.6457

[I 2026-07-11 18:18:51,315] Trial 88 finished with value: 0.5649647224407017 and parameters: {'num_leaves': 69, 'min_child_samples': 161}. Best is trial 40 with value: 0.5614106886949427.

Trial  88 | Validation MSE: 0.564965 | Unseen Pearson: 0.6598 | Unseen Spearman: 0.6426

[I 2026-07-11 18:19:39,995] Trial 89 finished with value: 0.5670748379708135 and parameters: {'num_leaves': 194, 'min_child_samples': 148}. Best is trial 40 with value: 0.5614106886949427.

Trial  89 | Validation MSE: 0.567075 | Unseen Pearson: 0.6611 | Unseen Spearman: 0.6439

[I 2026-07-11 18:19:59,167] Trial 90 finished with value: 0.5720626519302682 and parameters: {'num_leaves': 32, 'min_child_samples': 171}. Best is trial 40 with value: 0.5614106886949427.

Trial  90 | Validation MSE: 0.572063 | Unseen Pearson: 0.6541 | Unseen Spearman: 0.6374

[I 2026-07-11 18:20:45,242] Trial 91 finished with value: 0.5633491281433395 and parameters: {'num_leaves': 179, 'min_child_samples': 166}. Best is trial 40 with value: 0.5614106886949427.

Trial  91 | Validation MSE: 0.563349 | Unseen Pearson: 0.6616 | Unseen Spearman: 0.6447

[I 2026-07-11 18:21:38,020] Trial 92 finished with value: 0.561796361880533 and parameters: {'num_leaves': 182, 'min_child_samples': 168}. Best is trial 40 with value: 0.5614106886949427.

Trial  92 | Validation MSE: 0.561796 | Unseen Pearson: 0.6617 | Unseen Spearman: 0.6449

[I 2026-07-11 18:22:18,921] Trial 93 finished with value: 0.5637067388236457 and parameters: {'num_leaves': 171, 'min_child_samples': 179}. Best is trial 40 with value: 0.5614106886949427.

Trial  93 | Validation MSE: 0.563707 | Unseen Pearson: 0.6601 | Unseen Spearman: 0.6433

[I 2026-07-11 18:23:06,134] Trial 94 finished with value: 0.565112825961611 and parameters: {'num_leaves': 160, 'min_child_samples': 142}. Best is trial 40 with value: 0.5614106886949427.

Trial  94 | Validation MSE: 0.565113 | Unseen Pearson: 0.6624 | Unseen Spearman: 0.6458

[I 2026-07-11 18:23:41,339] Trial 95 finished with value: 0.5663374177821262 and parameters: {'num_leaves': 119, 'min_child_samples': 135}. Best is trial 40 with value: 0.5614106886949427.

Trial  95 | Validation MSE: 0.566337 | Unseen Pearson: 0.6606 | Unseen Spearman: 0.6436

[I 2026-07-11 18:24:30,554] Trial 96 finished with value: 0.5648349888581489 and parameters: {'num_leaves': 148, 'min_child_samples': 157}. Best is trial 40 with value: 0.5614106886949427.

Trial  96 | Validation MSE: 0.564835 | Unseen Pearson: 0.6611 | Unseen Spearman: 0.6442

[I 2026-07-11 18:25:12,361] Trial 97 finished with value: 0.5643543995283344 and parameters: {'num_leaves': 184, 'min_child_samples': 169}. Best is trial 40 with value: 0.5614106886949427.

Trial  97 | Validation MSE: 0.564354 | Unseen Pearson: 0.6608 | Unseen Spearman: 0.6439

[I 2026-07-11 18:26:03,036] Trial 98 finished with value: 0.5654837916516794 and parameters: {'num_leaves': 207, 'min_child_samples': 153}. Best is trial 40 with value: 0.5614106886949427.

Trial  98 | Validation MSE: 0.565484 | Unseen Pearson: 0.6619 | Unseen Spearman: 0.6449

[I 2026-07-11 18:26:39,181] Trial 99 finished with value: 0.5632270238606174 and parameters: {'num_leaves': 109, 'min_child_samples': 161}. Best is trial 40 with value: 0.5614106886949427.

Trial  99 | Validation MSE: 0.563227 | Unseen Pearson: 0.6616 | Unseen Spearman: 0.6445

## Save the three requested metrics and the best model

In [19]:
results_df = (
    pd.DataFrame(trial_records)
    .sort_values("trial")
    .reset_index(drop=True)
)

# Combined file
results_df.to_csv(
    OUTPUT_DIR / "all_100_trial_metrics.csv",
    index=False,
)

# Numeric-only files
results_df["validation_mse"].to_csv(
    OUTPUT_DIR / "Validation_loss.txt",
    index=False,
    header=False,
)

results_df["unseen_pearson"].to_csv(
    OUTPUT_DIR / "Unseen_Pearson.txt",
    index=False,
    header=False,
)

results_df["unseen_spearman"].to_csv(
    OUTPUT_DIR / "Unseen_Spearman.txt",
    index=False,
    header=False,
)

best_trial_number = study.best_trial.number
best_row = results_df.loc[
    results_df["trial"] == best_trial_number
].iloc[0]

best_model = trial_models[best_trial_number]

joblib.dump(
    {
        "model": best_model,
        "feature_columns": X_train.columns.tolist(),
        "best_trial": best_trial_number,
        "best_params": study.best_trial.params,
        "best_iteration": study.best_trial.user_attrs["best_iteration"],
        "split_seed": SPLIT_SEED,
        "validation_mse": float(best_row["validation_mse"]),
        "unseen_pearson": float(best_row["unseen_pearson"]),
        "unseen_spearman": float(best_row["unseen_spearman"]),
    },
    OUTPUT_DIR / "best_model.joblib",
)

with open(OUTPUT_DIR / "best_trial_summary.json", "w") as f:
    json.dump(
        {
            "best_trial": int(best_trial_number),
            "best_params": study.best_trial.params,
            "best_iteration": int(
                study.best_trial.user_attrs["best_iteration"]
            ),
            "validation_mse": float(best_row["validation_mse"]),
            "unseen_pearson": float(best_row["unseen_pearson"]),
            "unseen_spearman": float(best_row["unseen_spearman"]),
        },
        f,
        indent=2,
    )

display(results_df.head())

print("\nBest trial selected by validation MSE")
print("Trial:", best_trial_number)
print("Parameters:", study.best_trial.params)
print(f"Validation MSE: {best_row['validation_mse']:.6f}")
print(f"Unseen Pearson: {best_row['unseen_pearson']:.4f}")
print(f"Unseen Spearman: {best_row['unseen_spearman']:.4f}")
print("\nFiles saved in:", OUTPUT_DIR.resolve())

   trial  validation_mse  unseen_pearson  unseen_spearman
0      0        0.564963        0.662682         0.645836
1      1        0.567461        0.659578         0.642520
2      2        0.580180        0.652691         0.634932
3      3        0.570332        0.655088         0.638557
4      4        0.566825        0.658645         0.641800

Best trial selected by validation MSE
Trial: 40
Parameters: {'num_leaves': 125, 'min_child_samples': 122}
Validation MSE: 0.561411
Unseen Pearson: 0.6619
Unseen Spearman: 0.6439

Files saved in: /Users/zhangjiongyu/rs_dev/models/rs3_fixed_split_100_trials

## Optional: verify output files

In [21]:
for path in sorted(OUTPUT_DIR.iterdir()):
    print(path.name)

Unseen_Pearson.txt
Unseen_Spearman.txt
Validation_loss.txt
all_100_trial_metrics.csv
best_model.joblib
best_trial_summary.json