# RS3 Chen2013-only model: fixed split, 100 Optuna trials

Place this notebook in `rs_dev/code` and run all cells.

In [1]:
from pathlib import Path
import json, warnings, joblib
import lightgbm as lgb
import numpy as np
import optuna
import pandas as pd
from scipy.stats import pearsonr, spearmanr
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import StratifiedGroupKFold
from datasets import dataset_list
from core import get_feature_df

TRACR_FILTER = "Chen2013"
SPLIT_SEED = 42
OPTUNA_SEED = 42
MODEL_SEED = 42
N_TRIALS = 100
EARLY_STOPPING_ROUNDS = 10

PROCESSED_DIR = Path("../data/processed")
OUTPUT_DIR = Path("../models/rs3_chen2013_fixed_split_100_trials")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
TRAIN_NAMES_FILE = PROCESSED_DIR / "train_data_names.csv"
print("Output:", OUTPUT_DIR.resolve())

/opt/anaconda3/envs/rs_dev_venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Output: /Users/zhangjiongyu/CRISPR-modular-deep-learning_backup_copy_revision/Revision_existing_model_comparison/RS3/rs_dev/models/rs3_chen2013_fixed_split_100_trials

In [3]:
train_data_names = pd.read_csv(TRAIN_NAMES_FILE)["name"].dropna().astype(str).tolist()
train_data_list = [ds for ds in dataset_list if ds.name in train_data_names]

for ds in train_data_list:
    ds.load_data()
    ds.set_sgrnas()

sg_df_list = []
for ds in train_data_list:
    df = ds.get_sg_df(include_group=True, include_activity=True).copy()
    df["dataset"] = ds.name
    df["tracr"] = ds.tracr
    sg_df_list.append(df)

groups = (
    pd.concat(sg_df_list, ignore_index=True)
    .groupby("sgRNA Context Sequence", as_index=False)
    .agg(target=("sgRNA Target", lambda x: ", ".join(sorted({
        str(v).upper() for v in x if not pd.isna(v) and str(v).strip() != ""
    }))))
)
groups["target"] = groups.apply(
    lambda r: r["target"] if r["target"] != "" else r["sgRNA Context Sequence"],
    axis=1,
)

all_data = (
    pd.concat(sg_df_list, ignore_index=True)
    .merge(groups[["sgRNA Context Sequence", "target"]], on="sgRNA Context Sequence", how="inner")
    .sort_values(["dataset", "target"])
    .reset_index(drop=True)
)

all_data["sgRNA Activity"] = pd.to_numeric(all_data["sgRNA Activity"], errors="coerce")
all_data = all_data.dropna(subset=[
    "sgRNA Context Sequence", "sgRNA Activity", "dataset", "tracr", "target"
]).reset_index(drop=True)

print("Available tracr values:")
print(all_data["tracr"].value_counts(dropna=False))

filtered_data = all_data.loc[
    all_data["tracr"].astype(str) == TRACR_FILTER
].copy().reset_index(drop=True)

if filtered_data.empty:
    raise ValueError(f"No rows found for tracr={TRACR_FILTER!r}")

print("\nFiltered rows:", len(filtered_data))
display(filtered_data["dataset"].value_counts().rename("n").to_frame())

Available tracr values:
tracr
Hsu2013     29951
Chen2013    21136
Name: count, dtype: int64

Filtered rows: 21136

               n
dataset
Munoz2016  21136

In [5]:
outer = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=SPLIT_SEED)
seen_idx, unseen_idx = next(outer.split(
    filtered_data, y=filtered_data["dataset"], groups=filtered_data["target"]
))
seen_data = filtered_data.iloc[seen_idx].reset_index(drop=True)
unseen_data = filtered_data.iloc[unseen_idx].reset_index(drop=True)

inner = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=SPLIT_SEED)
train_idx, val_idx = next(inner.split(
    seen_data, y=seen_data["dataset"], groups=seen_data["target"]
))
train_data = seen_data.iloc[train_idx].reset_index(drop=True)
validation_data = seen_data.iloc[val_idx].reset_index(drop=True)

assert set(train_data["target"]).isdisjoint(set(validation_data["target"]))
assert set(train_data["target"]).isdisjoint(set(unseen_data["target"]))
assert set(validation_data["target"]).isdisjoint(set(unseen_data["target"]))

display(pd.DataFrame({
    "subset": ["train", "validation", "unseen"],
    "n_rows": [len(train_data), len(validation_data), len(unseen_data)],
    "fraction": [
        len(train_data)/len(filtered_data),
        len(validation_data)/len(filtered_data),
        len(unseen_data)/len(filtered_data),
    ],
}))

       subset  n_rows  fraction
0       train   12741  0.602810
1  validation    3177  0.150312
2      unseen    5218  0.246877

In [7]:
X_train = get_feature_df(train_data)
X_validation = get_feature_df(validation_data).reindex(columns=X_train.columns, fill_value=0)
X_unseen = get_feature_df(unseen_data).reindex(columns=X_train.columns, fill_value=0)

y_train = train_data["sgRNA Activity"].to_numpy(float)
y_validation = validation_data["sgRNA Activity"].to_numpy(float)
y_unseen = unseen_data["sgRNA Activity"].to_numpy(float)

print(X_train.shape, X_validation.shape, X_unseen.shape)

100%|███████████████████████████████████| 12741/12741 [00:02<00:00, 5195.33it/s]
100%|█████████████████████████████████████| 3177/3177 [00:00<00:00, 4790.10it/s]
100%|█████████████████████████████████████| 5218/5218 [00:01<00:00, 4146.15it/s]

(12741, 632) (3177, 632) (5218, 632)

In [9]:
def safe_pearson(y_true, y_pred):
    if len(y_true) < 2 or np.std(y_true) == 0 or np.std(y_pred) == 0:
        return np.nan
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return float(pearsonr(y_true, y_pred)[0])

def safe_spearman(y_true, y_pred):
    if len(y_true) < 2 or np.std(y_true) == 0 or np.std(y_pred) == 0:
        return np.nan
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return float(spearmanr(y_true, y_pred)[0])

In [11]:
trial_records = []
trial_models = {}

def objective(trial):
    model = lgb.LGBMRegressor(
        objective="regression",
        random_state=MODEL_SEED,
        n_jobs=-1,
        learning_rate=0.01,
        n_estimators=5000,
        num_leaves=trial.suggest_int("num_leaves", 8, 256),
        min_child_samples=trial.suggest_int("min_child_samples", 8, 256),
        verbosity=-1,
    )

    model.fit(
        X_train, y_train,
        eval_set=[(X_validation, y_validation)],
        eval_metric="mse",
        callbacks=[lgb.early_stopping(EARLY_STOPPING_ROUNDS, verbose=False)],
    )

    best_iteration = model.best_iteration_ or model.n_estimators
    val_pred = model.predict(X_validation, num_iteration=best_iteration)
    unseen_pred = model.predict(X_unseen, num_iteration=best_iteration)

    validation_mse = float(mean_squared_error(y_validation, val_pred))
    unseen_pearson = safe_pearson(y_unseen, unseen_pred)
    unseen_spearman = safe_spearman(y_unseen, unseen_pred)

    trial.set_user_attr("best_iteration", int(best_iteration))
    trial_records.append({
        "trial": trial.number,
        "validation_mse": validation_mse,
        "unseen_pearson": unseen_pearson,
        "unseen_spearman": unseen_spearman,
    })
    trial_models[trial.number] = model

    print(
        f"Trial {trial.number:3d} | Validation MSE: {validation_mse:.6f} | "
        f"Unseen Pearson: {unseen_pearson:.4f} | "
        f"Unseen Spearman: {unseen_spearman:.4f}"
    )
    return validation_mse

study = optuna.create_study(
    direction="minimize",
    sampler=optuna.samplers.TPESampler(seed=OPTUNA_SEED),
)
study.optimize(objective, n_trials=N_TRIALS)

[I 2026-07-15 21:30:42,186] A new study created in memory with name: no-name-38fee443-c59a-48ac-8846-4dae2ccef51f
[I 2026-07-15 21:30:57,897] Trial 0 finished with value: 0.7408824936866997 and parameters: {'num_leaves': 101, 'min_child_samples': 244}. Best is trial 0 with value: 0.7408824936866997.

Trial   0 | Validation MSE: 0.740882 | Unseen Pearson: 0.5050 | Unseen Spearman: 0.4721

[I 2026-07-15 21:31:15,794] Trial 1 finished with value: 0.7411326413576494 and parameters: {'num_leaves': 190, 'min_child_samples': 157}. Best is trial 0 with value: 0.7408824936866997.

Trial   1 | Validation MSE: 0.741133 | Unseen Pearson: 0.5034 | Unseen Spearman: 0.4677

[I 2026-07-15 21:31:32,505] Trial 2 finished with value: 0.7400234149758733 and parameters: {'num_leaves': 46, 'min_child_samples': 46}. Best is trial 2 with value: 0.7400234149758733.

Trial   2 | Validation MSE: 0.740023 | Unseen Pearson: 0.5106 | Unseen Spearman: 0.4709

[I 2026-07-15 21:31:41,069] Trial 3 finished with value: 0.7410869837434346 and parameters: {'num_leaves': 22, 'min_child_samples': 223}. Best is trial 2 with value: 0.7400234149758733.

Trial   3 | Validation MSE: 0.741087 | Unseen Pearson: 0.5033 | Unseen Spearman: 0.4694

[I 2026-07-15 21:31:57,823] Trial 4 finished with value: 0.7419845485756152 and parameters: {'num_leaves': 157, 'min_child_samples': 184}. Best is trial 2 with value: 0.7400234149758733.

Trial   4 | Validation MSE: 0.741985 | Unseen Pearson: 0.5052 | Unseen Spearman: 0.4717

[I 2026-07-15 21:32:05,206] Trial 5 finished with value: 0.7398410951713146 and parameters: {'num_leaves': 13, 'min_child_samples': 249}. Best is trial 5 with value: 0.7398410951713146.

Trial   5 | Validation MSE: 0.739841 | Unseen Pearson: 0.5019 | Unseen Spearman: 0.4674

[I 2026-07-15 21:32:44,719] Trial 6 finished with value: 0.7488606521676945 and parameters: {'num_leaves': 215, 'min_child_samples': 60}. Best is trial 5 with value: 0.7398410951713146.

Trial   6 | Validation MSE: 0.748861 | Unseen Pearson: 0.5036 | Unseen Spearman: 0.4655

[I 2026-07-15 21:33:02,538] Trial 7 finished with value: 0.7392516271691835 and parameters: {'num_leaves': 53, 'min_child_samples': 53}. Best is trial 7 with value: 0.7392516271691835.

Trial   7 | Validation MSE: 0.739252 | Unseen Pearson: 0.5086 | Unseen Spearman: 0.4702

[I 2026-07-15 21:33:22,434] Trial 8 finished with value: 0.7400284951211404 and parameters: {'num_leaves': 83, 'min_child_samples': 138}. Best is trial 7 with value: 0.7392516271691835.

Trial   8 | Validation MSE: 0.740028 | Unseen Pearson: 0.5052 | Unseen Spearman: 0.4690

[I 2026-07-15 21:33:47,007] Trial 9 finished with value: 0.7470791285276895 and parameters: {'num_leaves': 115, 'min_child_samples': 80}. Best is trial 7 with value: 0.7392516271691835.

Trial   9 | Validation MSE: 0.747079 | Unseen Pearson: 0.4995 | Unseen Spearman: 0.4630

[I 2026-07-15 21:34:54,121] Trial 10 finished with value: 0.7561092440373899 and parameters: {'num_leaves': 244, 'min_child_samples': 9}. Best is trial 7 with value: 0.7392516271691835.

Trial  10 | Validation MSE: 0.756109 | Unseen Pearson: 0.4921 | Unseen Spearman: 0.4546

[I 2026-07-15 21:35:01,566] Trial 11 finished with value: 0.7380467751809959 and parameters: {'num_leaves': 9, 'min_child_samples': 131}. Best is trial 11 with value: 0.7380467751809959.

Trial  11 | Validation MSE: 0.738047 | Unseen Pearson: 0.4995 | Unseen Spearman: 0.4617

[I 2026-07-15 21:35:21,298] Trial 12 finished with value: 0.7381307750813164 and parameters: {'num_leaves': 66, 'min_child_samples': 109}. Best is trial 11 with value: 0.7380467751809959.

Trial  12 | Validation MSE: 0.738131 | Unseen Pearson: 0.5037 | Unseen Spearman: 0.4662

[I 2026-07-15 21:35:43,963] Trial 13 finished with value: 0.7343157689226248 and parameters: {'num_leaves': 61, 'min_child_samples': 106}. Best is trial 13 with value: 0.7343157689226248.

Trial  13 | Validation MSE: 0.734316 | Unseen Pearson: 0.5081 | Unseen Spearman: 0.4695

[I 2026-07-15 21:36:03,169] Trial 14 finished with value: 0.74656758247285 and parameters: {'num_leaves': 131, 'min_child_samples': 113}. Best is trial 13 with value: 0.7343157689226248.

Trial  14 | Validation MSE: 0.746568 | Unseen Pearson: 0.4984 | Unseen Spearman: 0.4621

[I 2026-07-15 21:36:11,870] Trial 15 finished with value: 0.7356882388864815 and parameters: {'num_leaves': 12, 'min_child_samples': 181}. Best is trial 13 with value: 0.7343157689226248.

Trial  15 | Validation MSE: 0.735688 | Unseen Pearson: 0.5018 | Unseen Spearman: 0.4643

[I 2026-07-15 21:36:28,961] Trial 16 finished with value: 0.7346445900022704 and parameters: {'num_leaves': 39, 'min_child_samples': 178}. Best is trial 13 with value: 0.7343157689226248.

Trial  16 | Validation MSE: 0.734645 | Unseen Pearson: 0.5075 | Unseen Spearman: 0.4724

[I 2026-07-15 21:36:44,801] Trial 17 finished with value: 0.7410218508513631 and parameters: {'num_leaves': 81, 'min_child_samples': 202}. Best is trial 13 with value: 0.7343157689226248.

Trial  17 | Validation MSE: 0.741022 | Unseen Pearson: 0.5023 | Unseen Spearman: 0.4684

[I 2026-07-15 21:37:00,562] Trial 18 finished with value: 0.7395181569750648 and parameters: {'num_leaves': 47, 'min_child_samples': 159}. Best is trial 13 with value: 0.7343157689226248.

Trial  18 | Validation MSE: 0.739518 | Unseen Pearson: 0.5044 | Unseen Spearman: 0.4683

[I 2026-07-15 21:37:28,947] Trial 19 finished with value: 0.743319516999806 and parameters: {'num_leaves': 135, 'min_child_samples': 89}. Best is trial 13 with value: 0.7343157689226248.

Trial  19 | Validation MSE: 0.743320 | Unseen Pearson: 0.5029 | Unseen Spearman: 0.4656

[I 2026-07-15 21:37:42,568] Trial 20 finished with value: 0.7448415807399648 and parameters: {'num_leaves': 38, 'min_child_samples': 14}. Best is trial 13 with value: 0.7343157689226248.

Trial  20 | Validation MSE: 0.744842 | Unseen Pearson: 0.5086 | Unseen Spearman: 0.4690

[I 2026-07-15 21:37:57,314] Trial 21 finished with value: 0.73378901191416 and parameters: {'num_leaves': 31, 'min_child_samples': 181}. Best is trial 21 with value: 0.73378901191416.

Trial  21 | Validation MSE: 0.733789 | Unseen Pearson: 0.5086 | Unseen Spearman: 0.4731

[I 2026-07-15 21:38:14,421] Trial 22 finished with value: 0.741301489168543 and parameters: {'num_leaves': 76, 'min_child_samples': 210}. Best is trial 21 with value: 0.73378901191416.

Trial  22 | Validation MSE: 0.741301 | Unseen Pearson: 0.5061 | Unseen Spearman: 0.4729

[I 2026-07-15 21:38:27,604] Trial 23 finished with value: 0.7375997415705181 and parameters: {'num_leaves': 39, 'min_child_samples': 168}. Best is trial 21 with value: 0.73378901191416.

Trial  23 | Validation MSE: 0.737600 | Unseen Pearson: 0.5070 | Unseen Spearman: 0.4718

[I 2026-07-15 21:38:46,159] Trial 24 finished with value: 0.7374976703290561 and parameters: {'num_leaves': 98, 'min_child_samples': 137}. Best is trial 21 with value: 0.73378901191416.

Trial  24 | Validation MSE: 0.737498 | Unseen Pearson: 0.5045 | Unseen Spearman: 0.4683

[I 2026-07-15 21:39:04,322] Trial 25 finished with value: 0.7391510383304268 and parameters: {'num_leaves': 59, 'min_child_samples': 194}. Best is trial 21 with value: 0.73378901191416.

Trial  25 | Validation MSE: 0.739151 | Unseen Pearson: 0.5039 | Unseen Spearman: 0.4693

[I 2026-07-15 21:39:20,797] Trial 26 finished with value: 0.7365869820093807 and parameters: {'num_leaves': 32, 'min_child_samples': 227}. Best is trial 21 with value: 0.73378901191416.

Trial  26 | Validation MSE: 0.736587 | Unseen Pearson: 0.5072 | Unseen Spearman: 0.4733

[I 2026-07-15 21:39:44,750] Trial 27 finished with value: 0.7399929929487573 and parameters: {'num_leaves': 66, 'min_child_samples': 116}. Best is trial 21 with value: 0.73378901191416.

Trial  27 | Validation MSE: 0.739993 | Unseen Pearson: 0.5058 | Unseen Spearman: 0.4679

[I 2026-07-15 21:39:59,815] Trial 28 finished with value: 0.7309392896594816 and parameters: {'num_leaves': 29, 'min_child_samples': 151}. Best is trial 28 with value: 0.7309392896594816.

Trial  28 | Validation MSE: 0.730939 | Unseen Pearson: 0.5073 | Unseen Spearman: 0.4694

[I 2026-07-15 21:40:28,313] Trial 29 finished with value: 0.7445425214870979 and parameters: {'num_leaves': 97, 'min_child_samples': 86}. Best is trial 28 with value: 0.7309392896594816.

Trial  29 | Validation MSE: 0.744543 | Unseen Pearson: 0.5042 | Unseen Spearman: 0.4677

[I 2026-07-15 21:40:42,207] Trial 30 finished with value: 0.7323438033323516 and parameters: {'num_leaves': 27, 'min_child_samples': 147}. Best is trial 28 with value: 0.7309392896594816.

Trial  30 | Validation MSE: 0.732344 | Unseen Pearson: 0.5066 | Unseen Spearman: 0.4697

[I 2026-07-15 21:40:55,014] Trial 31 finished with value: 0.7297199787020581 and parameters: {'num_leaves': 26, 'min_child_samples': 145}. Best is trial 31 with value: 0.7297199787020581.

Trial  31 | Validation MSE: 0.729720 | Unseen Pearson: 0.5071 | Unseen Spearman: 0.4690

[I 2026-07-15 21:41:05,787] Trial 32 finished with value: 0.7359217365737263 and parameters: {'num_leaves': 27, 'min_child_samples': 156}. Best is trial 31 with value: 0.7297199787020581.

Trial  32 | Validation MSE: 0.735922 | Unseen Pearson: 0.5041 | Unseen Spearman: 0.4670

[I 2026-07-15 21:41:18,645] Trial 33 finished with value: 0.7343417849543818 and parameters: {'num_leaves': 26, 'min_child_samples': 148}. Best is trial 31 with value: 0.7297199787020581.

Trial  33 | Validation MSE: 0.734342 | Unseen Pearson: 0.5049 | Unseen Spearman: 0.4673

[I 2026-07-15 21:41:25,877] Trial 34 finished with value: 0.7388415315834909 and parameters: {'num_leaves': 10, 'min_child_samples': 169}. Best is trial 31 with value: 0.7297199787020581.

Trial  34 | Validation MSE: 0.738842 | Unseen Pearson: 0.4981 | Unseen Spearman: 0.4614

[I 2026-07-15 21:41:39,739] Trial 35 finished with value: 0.7345075182980442 and parameters: {'num_leaves': 26, 'min_child_samples': 127}. Best is trial 31 with value: 0.7297199787020581.

Trial  35 | Validation MSE: 0.734508 | Unseen Pearson: 0.5053 | Unseen Spearman: 0.4676

[I 2026-07-15 21:41:58,859] Trial 36 finished with value: 0.7347305189408455 and parameters: {'num_leaves': 53, 'min_child_samples': 154}. Best is trial 31 with value: 0.7297199787020581.

Trial  36 | Validation MSE: 0.734731 | Unseen Pearson: 0.5063 | Unseen Spearman: 0.4706

[I 2026-07-15 21:42:07,860] Trial 37 finished with value: 0.7391572893959675 and parameters: {'num_leaves': 21, 'min_child_samples': 214}. Best is trial 31 with value: 0.7297199787020581.

Trial  37 | Validation MSE: 0.739157 | Unseen Pearson: 0.5043 | Unseen Spearman: 0.4699

[I 2026-07-15 21:42:17,769] Trial 38 finished with value: 0.7510908622733594 and parameters: {'num_leaves': 43, 'min_child_samples': 228}. Best is trial 31 with value: 0.7297199787020581.

Trial  38 | Validation MSE: 0.751091 | Unseen Pearson: 0.4986 | Unseen Spearman: 0.4673

[I 2026-07-15 21:42:36,861] Trial 39 finished with value: 0.7391510383304268 and parameters: {'num_leaves': 172, 'min_child_samples': 194}. Best is trial 31 with value: 0.7297199787020581.

Trial  39 | Validation MSE: 0.739151 | Unseen Pearson: 0.5039 | Unseen Spearman: 0.4693

[I 2026-07-15 21:42:58,632] Trial 40 finished with value: 0.7350000688426553 and parameters: {'num_leaves': 75, 'min_child_samples': 147}. Best is trial 31 with value: 0.7297199787020581.

Trial  40 | Validation MSE: 0.735000 | Unseen Pearson: 0.5058 | Unseen Spearman: 0.4701

[I 2026-07-15 21:43:21,250] Trial 41 finished with value: 0.734619519765823 and parameters: {'num_leaves': 58, 'min_child_samples': 96}. Best is trial 31 with value: 0.7297199787020581.

Trial  41 | Validation MSE: 0.734620 | Unseen Pearson: 0.5093 | Unseen Spearman: 0.4703

[I 2026-07-15 21:43:31,404] Trial 42 finished with value: 0.7381635428444311 and parameters: {'num_leaves': 22, 'min_child_samples': 67}. Best is trial 31 with value: 0.7297199787020581.

Trial  42 | Validation MSE: 0.738164 | Unseen Pearson: 0.5039 | Unseen Spearman: 0.4646

[I 2026-07-15 21:43:49,185] Trial 43 finished with value: 0.7374101953286956 and parameters: {'num_leaves': 48, 'min_child_samples': 106}. Best is trial 31 with value: 0.7297199787020581.

Trial  43 | Validation MSE: 0.737410 | Unseen Pearson: 0.5047 | Unseen Spearman: 0.4663

[I 2026-07-15 21:44:08,563] Trial 44 finished with value: 0.7395542468786311 and parameters: {'num_leaves': 65, 'min_child_samples': 126}. Best is trial 31 with value: 0.7297199787020581.

Trial  44 | Validation MSE: 0.739554 | Unseen Pearson: 0.5043 | Unseen Spearman: 0.4682

[I 2026-07-15 21:44:15,930] Trial 45 finished with value: 0.7409511813468893 and parameters: {'num_leaves': 18, 'min_child_samples': 170}. Best is trial 31 with value: 0.7297199787020581.

Trial  45 | Validation MSE: 0.740951 | Unseen Pearson: 0.4995 | Unseen Spearman: 0.4632

[I 2026-07-15 21:44:29,628] Trial 46 finished with value: 0.7370420199543861 and parameters: {'num_leaves': 35, 'min_child_samples': 142}. Best is trial 31 with value: 0.7297199787020581.

Trial  46 | Validation MSE: 0.737042 | Unseen Pearson: 0.5085 | Unseen Spearman: 0.4722

[I 2026-07-15 21:44:48,950] Trial 47 finished with value: 0.7425751645806392 and parameters: {'num_leaves': 92, 'min_child_samples': 122}. Best is trial 31 with value: 0.7297199787020581.

Trial  47 | Validation MSE: 0.742575 | Unseen Pearson: 0.5034 | Unseen Spearman: 0.4680

[I 2026-07-15 21:45:19,938] Trial 48 finished with value: 0.7450259617412927 and parameters: {'num_leaves': 115, 'min_child_samples': 32}. Best is trial 31 with value: 0.7297199787020581.

Trial  48 | Validation MSE: 0.745026 | Unseen Pearson: 0.5080 | Unseen Spearman: 0.4701

[I 2026-07-15 21:45:28,119] Trial 49 finished with value: 0.7392822448334101 and parameters: {'num_leaves': 8, 'min_child_samples': 105}. Best is trial 31 with value: 0.7297199787020581.

Trial  49 | Validation MSE: 0.739282 | Unseen Pearson: 0.4950 | Unseen Spearman: 0.4567

[I 2026-07-15 21:45:44,285] Trial 50 finished with value: 0.7419845485756152 and parameters: {'num_leaves': 225, 'min_child_samples': 184}. Best is trial 31 with value: 0.7297199787020581.

Trial  50 | Validation MSE: 0.741985 | Unseen Pearson: 0.5052 | Unseen Spearman: 0.4717

[I 2026-07-15 21:45:56,469] Trial 51 finished with value: 0.73155581935048 and parameters: {'num_leaves': 26, 'min_child_samples': 149}. Best is trial 31 with value: 0.7297199787020581.

Trial  51 | Validation MSE: 0.731556 | Unseen Pearson: 0.5087 | Unseen Spearman: 0.4708

[I 2026-07-15 21:46:11,287] Trial 52 finished with value: 0.7392886606419365 and parameters: {'num_leaves': 49, 'min_child_samples': 162}. Best is trial 31 with value: 0.7297199787020581.

Trial  52 | Validation MSE: 0.739289 | Unseen Pearson: 0.5030 | Unseen Spearman: 0.4679

[I 2026-07-15 21:46:25,436] Trial 53 finished with value: 0.7363158184604729 and parameters: {'num_leaves': 34, 'min_child_samples': 143}. Best is trial 31 with value: 0.7297199787020581.

Trial  53 | Validation MSE: 0.736316 | Unseen Pearson: 0.5084 | Unseen Spearman: 0.4707

[I 2026-07-15 21:46:36,119] Trial 54 finished with value: 0.7346923496652529 and parameters: {'num_leaves': 18, 'min_child_samples': 133}. Best is trial 31 with value: 0.7297199787020581.

Trial  54 | Validation MSE: 0.734692 | Unseen Pearson: 0.5030 | Unseen Spearman: 0.4651

[I 2026-07-15 21:46:55,764] Trial 55 finished with value: 0.7386981426496105 and parameters: {'num_leaves': 71, 'min_child_samples': 174}. Best is trial 31 with value: 0.7297199787020581.

Trial  55 | Validation MSE: 0.738698 | Unseen Pearson: 0.5038 | Unseen Spearman: 0.4687

[I 2026-07-15 21:47:13,356] Trial 56 finished with value: 0.7431383260662258 and parameters: {'num_leaves': 56, 'min_child_samples': 189}. Best is trial 31 with value: 0.7297199787020581.

Trial  56 | Validation MSE: 0.743138 | Unseen Pearson: 0.5014 | Unseen Spearman: 0.4675

[I 2026-07-15 21:47:28,435] Trial 57 finished with value: 0.7381483193065046 and parameters: {'num_leaves': 44, 'min_child_samples': 159}. Best is trial 31 with value: 0.7297199787020581.

Trial  57 | Validation MSE: 0.738148 | Unseen Pearson: 0.5060 | Unseen Spearman: 0.4701

[I 2026-07-15 21:47:51,047] Trial 58 finished with value: 0.7440240490033336 and parameters: {'num_leaves': 87, 'min_child_samples': 117}. Best is trial 31 with value: 0.7297199787020581.

Trial  58 | Validation MSE: 0.744024 | Unseen Pearson: 0.5025 | Unseen Spearman: 0.4654

[I 2026-07-15 21:48:04,105] Trial 59 finished with value: 0.7377620663852162 and parameters: {'num_leaves': 30, 'min_child_samples': 69}. Best is trial 31 with value: 0.7297199787020581.

Trial  59 | Validation MSE: 0.737762 | Unseen Pearson: 0.5073 | Unseen Spearman: 0.4681

[I 2026-07-15 21:48:14,874] Trial 60 finished with value: 0.7316635666022098 and parameters: {'num_leaves': 17, 'min_child_samples': 97}. Best is trial 31 with value: 0.7297199787020581.

Trial  60 | Validation MSE: 0.731664 | Unseen Pearson: 0.5021 | Unseen Spearman: 0.4628

[I 2026-07-15 21:48:25,527] Trial 61 finished with value: 0.7328523008265603 and parameters: {'num_leaves': 20, 'min_child_samples': 99}. Best is trial 31 with value: 0.7297199787020581.

Trial  61 | Validation MSE: 0.732852 | Unseen Pearson: 0.5025 | Unseen Spearman: 0.4642

[I 2026-07-15 21:48:35,156] Trial 62 finished with value: 0.7332637492230679 and parameters: {'num_leaves': 16, 'min_child_samples': 99}. Best is trial 31 with value: 0.7297199787020581.

Trial  62 | Validation MSE: 0.733264 | Unseen Pearson: 0.5015 | Unseen Spearman: 0.4631

[I 2026-07-15 21:48:45,661] Trial 63 finished with value: 0.7345430584513729 and parameters: {'num_leaves': 12, 'min_child_samples': 97}. Best is trial 31 with value: 0.7297199787020581.

Trial  63 | Validation MSE: 0.734543 | Unseen Pearson: 0.5001 | Unseen Spearman: 0.4609

[I 2026-07-15 21:48:54,357] Trial 64 finished with value: 0.7363309795686495 and parameters: {'num_leaves': 17, 'min_child_samples': 76}. Best is trial 31 with value: 0.7297199787020581.

Trial  64 | Validation MSE: 0.736331 | Unseen Pearson: 0.5016 | Unseen Spearman: 0.4620

[I 2026-07-15 21:49:12,207] Trial 65 finished with value: 0.7339995982596998 and parameters: {'num_leaves': 40, 'min_child_samples': 98}. Best is trial 31 with value: 0.7297199787020581.

Trial  65 | Validation MSE: 0.734000 | Unseen Pearson: 0.5063 | Unseen Spearman: 0.4681

[I 2026-07-15 21:49:23,980] Trial 66 finished with value: 0.732456142150598 and parameters: {'num_leaves': 25, 'min_child_samples': 84}. Best is trial 31 with value: 0.7297199787020581.

Trial  66 | Validation MSE: 0.732456 | Unseen Pearson: 0.5038 | Unseen Spearman: 0.4651

[I 2026-07-15 21:49:36,649] Trial 67 finished with value: 0.7369976373672378 and parameters: {'num_leaves': 24, 'min_child_samples': 48}. Best is trial 31 with value: 0.7297199787020581.

Trial  67 | Validation MSE: 0.736998 | Unseen Pearson: 0.5079 | Unseen Spearman: 0.4687

[I 2026-07-15 21:49:51,653] Trial 68 finished with value: 0.7305597205131511 and parameters: {'num_leaves': 34, 'min_child_samples': 85}. Best is trial 31 with value: 0.7297199787020581.

Trial  68 | Validation MSE: 0.730560 | Unseen Pearson: 0.5078 | Unseen Spearman: 0.4695

[I 2026-07-15 21:50:05,282] Trial 69 finished with value: 0.7423777915423629 and parameters: {'num_leaves': 32, 'min_child_samples': 36}. Best is trial 31 with value: 0.7297199787020581.

Trial  69 | Validation MSE: 0.742378 | Unseen Pearson: 0.5102 | Unseen Spearman: 0.4722

[I 2026-07-15 21:50:20,519] Trial 70 finished with value: 0.7406723874470406 and parameters: {'num_leaves': 47, 'min_child_samples': 57}. Best is trial 31 with value: 0.7297199787020581.

Trial  70 | Validation MSE: 0.740672 | Unseen Pearson: 0.5041 | Unseen Spearman: 0.4659

[I 2026-07-15 21:50:35,423] Trial 71 finished with value: 0.7333216826141818 and parameters: {'num_leaves': 38, 'min_child_samples': 79}. Best is trial 31 with value: 0.7297199787020581.

Trial  71 | Validation MSE: 0.733322 | Unseen Pearson: 0.5078 | Unseen Spearman: 0.4693

[I 2026-07-15 21:50:42,613] Trial 72 finished with value: 0.738377412723597 and parameters: {'num_leaves': 9, 'min_child_samples': 92}. Best is trial 31 with value: 0.7297199787020581.

Trial  72 | Validation MSE: 0.738377 | Unseen Pearson: 0.4957 | Unseen Spearman: 0.4572

[I 2026-07-15 21:50:54,046] Trial 73 finished with value: 0.7345465385703074 and parameters: {'num_leaves': 26, 'min_child_samples': 84}. Best is trial 31 with value: 0.7297199787020581.

Trial  73 | Validation MSE: 0.734547 | Unseen Pearson: 0.5051 | Unseen Spearman: 0.4670

[I 2026-07-15 21:51:05,527] Trial 74 finished with value: 0.7318167408749517 and parameters: {'num_leaves': 19, 'min_child_samples': 152}. Best is trial 31 with value: 0.7297199787020581.

Trial  74 | Validation MSE: 0.731817 | Unseen Pearson: 0.5048 | Unseen Spearman: 0.4669

[I 2026-07-15 21:51:20,352] Trial 75 finished with value: 0.7433323982827911 and parameters: {'num_leaves': 53, 'min_child_samples': 152}. Best is trial 31 with value: 0.7297199787020581.

Trial  75 | Validation MSE: 0.743332 | Unseen Pearson: 0.4994 | Unseen Spearman: 0.4640

[I 2026-07-15 21:51:36,928] Trial 76 finished with value: 0.7312723720361612 and parameters: {'num_leaves': 30, 'min_child_samples': 136}. Best is trial 31 with value: 0.7297199787020581.

Trial  76 | Validation MSE: 0.731272 | Unseen Pearson: 0.5083 | Unseen Spearman: 0.4704

[I 2026-07-15 21:51:52,274] Trial 77 finished with value: 0.7356070731927717 and parameters: {'num_leaves': 34, 'min_child_samples': 131}. Best is trial 31 with value: 0.7297199787020581.

Trial  77 | Validation MSE: 0.735607 | Unseen Pearson: 0.5071 | Unseen Spearman: 0.4700

[I 2026-07-15 21:52:08,451] Trial 78 finished with value: 0.7351030055766541 and parameters: {'num_leaves': 42, 'min_child_samples': 138}. Best is trial 31 with value: 0.7297199787020581.

Trial  78 | Validation MSE: 0.735103 | Unseen Pearson: 0.5079 | Unseen Spearman: 0.4721

[I 2026-07-15 21:52:17,317] Trial 79 finished with value: 0.7371282980379081 and parameters: {'num_leaves': 14, 'min_child_samples': 162}. Best is trial 31 with value: 0.7297199787020581.

Trial  79 | Validation MSE: 0.737128 | Unseen Pearson: 0.5011 | Unseen Spearman: 0.4637

[I 2026-07-15 21:52:31,824] Trial 80 finished with value: 0.7339054396804062 and parameters: {'num_leaves': 30, 'min_child_samples': 149}. Best is trial 31 with value: 0.7297199787020581.

Trial  80 | Validation MSE: 0.733905 | Unseen Pearson: 0.5072 | Unseen Spearman: 0.4700

[I 2026-07-15 21:52:45,736] Trial 81 finished with value: 0.7300660282237273 and parameters: {'num_leaves': 26, 'min_child_samples': 118}. Best is trial 31 with value: 0.7297199787020581.

Trial  81 | Validation MSE: 0.730066 | Unseen Pearson: 0.5084 | Unseen Spearman: 0.4698

[I 2026-07-15 21:52:54,356] Trial 82 finished with value: 0.7388106035559638 and parameters: {'num_leaves': 8, 'min_child_samples': 122}. Best is trial 31 with value: 0.7297199787020581.

Trial  82 | Validation MSE: 0.738811 | Unseen Pearson: 0.4955 | Unseen Spearman: 0.4570

[I 2026-07-15 21:53:05,879] Trial 83 finished with value: 0.7337055573292212 and parameters: {'num_leaves': 21, 'min_child_samples': 112}. Best is trial 31 with value: 0.7297199787020581.

Trial  83 | Validation MSE: 0.733706 | Unseen Pearson: 0.5046 | Unseen Spearman: 0.4656

[I 2026-07-15 21:53:22,459] Trial 84 finished with value: 0.7338392178440191 and parameters: {'num_leaves': 39, 'min_child_samples': 136}. Best is trial 31 with value: 0.7297199787020581.

Trial  84 | Validation MSE: 0.733839 | Unseen Pearson: 0.5079 | Unseen Spearman: 0.4710

[I 2026-07-15 21:53:38,329] Trial 85 finished with value: 0.732580944189586 and parameters: {'num_leaves': 29, 'min_child_samples': 127}. Best is trial 31 with value: 0.7297199787020581.

Trial  85 | Validation MSE: 0.732581 | Unseen Pearson: 0.5073 | Unseen Spearman: 0.4696

[I 2026-07-15 21:53:48,370] Trial 86 finished with value: 0.7368873037500606 and parameters: {'num_leaves': 15, 'min_child_samples': 145}. Best is trial 31 with value: 0.7297199787020581.

Trial  86 | Validation MSE: 0.736887 | Unseen Pearson: 0.5020 | Unseen Spearman: 0.4637

[I 2026-07-15 21:54:03,768] Trial 87 finished with value: 0.7405880290286713 and parameters: {'num_leaves': 51, 'min_child_samples': 119}. Best is trial 31 with value: 0.7297199787020581.

Trial  87 | Validation MSE: 0.740588 | Unseen Pearson: 0.5034 | Unseen Spearman: 0.4674

[I 2026-07-15 21:54:21,654] Trial 88 finished with value: 0.7388882502749758 and parameters: {'num_leaves': 45, 'min_child_samples': 168}. Best is trial 31 with value: 0.7297199787020581.

Trial  88 | Validation MSE: 0.738888 | Unseen Pearson: 0.5042 | Unseen Spearman: 0.4700

[I 2026-07-15 21:54:40,222] Trial 89 finished with value: 0.7386246077493512 and parameters: {'num_leaves': 63, 'min_child_samples': 156}. Best is trial 31 with value: 0.7297199787020581.

Trial  89 | Validation MSE: 0.738625 | Unseen Pearson: 0.5036 | Unseen Spearman: 0.4682

[I 2026-07-15 21:54:55,454] Trial 90 finished with value: 0.7366023456853212 and parameters: {'num_leaves': 36, 'min_child_samples': 142}. Best is trial 31 with value: 0.7297199787020581.

Trial  90 | Validation MSE: 0.736602 | Unseen Pearson: 0.5082 | Unseen Spearman: 0.4708

[I 2026-07-15 21:55:06,872] Trial 91 finished with value: 0.7375700686896492 and parameters: {'num_leaves': 24, 'min_child_samples': 72}. Best is trial 31 with value: 0.7297199787020581.

Trial  91 | Validation MSE: 0.737570 | Unseen Pearson: 0.5036 | Unseen Spearman: 0.4648

[I 2026-07-15 21:55:18,435] Trial 92 finished with value: 0.7358625349057372 and parameters: {'num_leaves': 27, 'min_child_samples': 109}. Best is trial 31 with value: 0.7297199787020581.

Trial  92 | Validation MSE: 0.735863 | Unseen Pearson: 0.5031 | Unseen Spearman: 0.4651

[I 2026-07-15 21:55:29,915] Trial 93 finished with value: 0.7345275235380649 and parameters: {'num_leaves': 21, 'min_child_samples': 91}. Best is trial 31 with value: 0.7297199787020581.

Trial  93 | Validation MSE: 0.734528 | Unseen Pearson: 0.5031 | Unseen Spearman: 0.4649

[I 2026-07-15 21:55:39,164] Trial 94 finished with value: 0.7376496650395453 and parameters: {'num_leaves': 15, 'min_child_samples': 153}. Best is trial 31 with value: 0.7297199787020581.

Trial  94 | Validation MSE: 0.737650 | Unseen Pearson: 0.5018 | Unseen Spearman: 0.4641

[I 2026-07-15 21:55:52,122] Trial 95 finished with value: 0.7359775679686448 and parameters: {'num_leaves': 30, 'min_child_samples': 63}. Best is trial 31 with value: 0.7297199787020581.

Trial  95 | Validation MSE: 0.735978 | Unseen Pearson: 0.5074 | Unseen Spearman: 0.4682

[I 2026-07-15 21:56:13,170] Trial 96 finished with value: 0.7353095290684338 and parameters: {'num_leaves': 250, 'min_child_samples': 163}. Best is trial 31 with value: 0.7297199787020581.

Trial  96 | Validation MSE: 0.735310 | Unseen Pearson: 0.5057 | Unseen Spearman: 0.4698

[I 2026-07-15 21:56:26,729] Trial 97 finished with value: 0.7394900835013665 and parameters: {'num_leaves': 42, 'min_child_samples': 130}. Best is trial 31 with value: 0.7297199787020581.

Trial  97 | Validation MSE: 0.739490 | Unseen Pearson: 0.5039 | Unseen Spearman: 0.4683

[I 2026-07-15 21:56:39,671] Trial 98 finished with value: 0.7363328498294943 and parameters: {'num_leaves': 34, 'min_child_samples': 174}. Best is trial 31 with value: 0.7297199787020581.

Trial  98 | Validation MSE: 0.736333 | Unseen Pearson: 0.5060 | Unseen Spearman: 0.4712

[I 2026-07-15 21:56:51,084] Trial 99 finished with value: 0.7338446588042903 and parameters: {'num_leaves': 23, 'min_child_samples': 84}. Best is trial 31 with value: 0.7297199787020581.

Trial  99 | Validation MSE: 0.733845 | Unseen Pearson: 0.5029 | Unseen Spearman: 0.4647

In [13]:
results_df = pd.DataFrame(trial_records).sort_values("trial").reset_index(drop=True)
results_df.to_csv(OUTPUT_DIR / "all_100_trial_metrics.csv", index=False)
results_df["validation_mse"].to_csv(OUTPUT_DIR / "Validation_loss.txt", index=False, header=False)
results_df["unseen_pearson"].to_csv(OUTPUT_DIR / "Unseen_Pearson.txt", index=False, header=False)
results_df["unseen_spearman"].to_csv(OUTPUT_DIR / "Unseen_Spearman.txt", index=False, header=False)

best_trial = study.best_trial.number
best_row = results_df.loc[results_df["trial"] == best_trial].iloc[0]
best_model = trial_models[best_trial]

joblib.dump({
    "model": best_model,
    "tracr": TRACR_FILTER,
    "feature_columns": X_train.columns.tolist(),
    "best_trial": best_trial,
    "best_params": study.best_trial.params,
    "best_iteration": study.best_trial.user_attrs["best_iteration"],
    "validation_mse": float(best_row["validation_mse"]),
    "unseen_pearson": float(best_row["unseen_pearson"]),
    "unseen_spearman": float(best_row["unseen_spearman"]),
}, OUTPUT_DIR / "best_model.joblib")

with open(OUTPUT_DIR / "best_trial_summary.json", "w") as f:
    json.dump({
        "tracr": TRACR_FILTER,
        "best_trial": int(best_trial),
        "best_params": study.best_trial.params,
        "best_iteration": int(study.best_trial.user_attrs["best_iteration"]),
        "validation_mse": float(best_row["validation_mse"]),
        "unseen_pearson": float(best_row["unseen_pearson"]),
        "unseen_spearman": float(best_row["unseen_spearman"]),
    }, f, indent=2)

display(results_df.head())
print("\nBest trial:", best_trial)
print(best_row[["validation_mse", "unseen_pearson", "unseen_spearman"]])
print("Saved to:", OUTPUT_DIR.resolve())

   trial  validation_mse  unseen_pearson  unseen_spearman
0      0        0.740882        0.505017         0.472079
1      1        0.741133        0.503406         0.467731
2      2        0.740023        0.510556         0.470870
3      3        0.741087        0.503310         0.469415
4      4        0.741985        0.505215         0.471704

Best trial: 31
validation_mse     0.729720
unseen_pearson     0.507080
unseen_spearman    0.468985
Name: 31, dtype: float64
Saved to: /Users/zhangjiongyu/CRISPR-modular-deep-learning_backup_copy_revision/Revision_existing_model_comparison/RS3/rs_dev/models/rs3_chen2013_fixed_split_100_trials